package com.x.ic.smc.sdk.cache.vo;

import java.util.Date;

public class ElementAttr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.ATTR_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long attrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.TENANT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.ELEMENT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long elementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.sub_object_id
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String subObjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.SUB_ELEMENT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long subElementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.REL_TYPE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String relType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.REL_VALUE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String relValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.UPDATE_DEPT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String updateDeptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.UPDATE_OPER_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String updateOperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.UPDATE_TIME
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element_attr.POLICY_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long policyId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.ATTR_ID
	 * @return  the value of stl_element_attr.ATTR_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getAttrId() {
		return attrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.ATTR_ID
	 * @param attrId  the value for stl_element_attr.ATTR_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setAttrId(Long attrId) {
		this.attrId = attrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.TENANT_ID
	 * @return  the value of stl_element_attr.TENANT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.TENANT_ID
	 * @param tenantId  the value for stl_element_attr.TENANT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.ELEMENT_ID
	 * @return  the value of stl_element_attr.ELEMENT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getElementId() {
		return elementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.ELEMENT_ID
	 * @param elementId  the value for stl_element_attr.ELEMENT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setElementId(Long elementId) {
		this.elementId = elementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.sub_object_id
	 * @return  the value of stl_element_attr.sub_object_id
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getSubObjectId() {
		return subObjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.sub_object_id
	 * @param subObjectId  the value for stl_element_attr.sub_object_id
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setSubObjectId(String subObjectId) {
		this.subObjectId = subObjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.SUB_ELEMENT_ID
	 * @return  the value of stl_element_attr.SUB_ELEMENT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getSubElementId() {
		return subElementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.SUB_ELEMENT_ID
	 * @param subElementId  the value for stl_element_attr.SUB_ELEMENT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setSubElementId(Long subElementId) {
		this.subElementId = subElementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.REL_TYPE
	 * @return  the value of stl_element_attr.REL_TYPE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getRelType() {
		return relType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.REL_TYPE
	 * @param relType  the value for stl_element_attr.REL_TYPE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setRelType(String relType) {
		this.relType = relType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.REL_VALUE
	 * @return  the value of stl_element_attr.REL_VALUE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getRelValue() {
		return relValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.REL_VALUE
	 * @param relValue  the value for stl_element_attr.REL_VALUE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setRelValue(String relValue) {
		this.relValue = relValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.UPDATE_DEPT_ID
	 * @return  the value of stl_element_attr.UPDATE_DEPT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getUpdateDeptId() {
		return updateDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.UPDATE_DEPT_ID
	 * @param updateDeptId  the value for stl_element_attr.UPDATE_DEPT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setUpdateDeptId(String updateDeptId) {
		this.updateDeptId = updateDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.UPDATE_OPER_ID
	 * @return  the value of stl_element_attr.UPDATE_OPER_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getUpdateOperId() {
		return updateOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.UPDATE_OPER_ID
	 * @param updateOperId  the value for stl_element_attr.UPDATE_OPER_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setUpdateOperId(String updateOperId) {
		this.updateOperId = updateOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.UPDATE_TIME
	 * @return  the value of stl_element_attr.UPDATE_TIME
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.UPDATE_TIME
	 * @param updateTime  the value for stl_element_attr.UPDATE_TIME
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element_attr.POLICY_ID
	 * @return  the value of stl_element_attr.POLICY_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element_attr.POLICY_ID
	 * @param policyId  the value for stl_element_attr.POLICY_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setPolicyId(Long policyId) {
		this.policyId = policyId;
	}
}