package com.x.ic.smc.sdk.cache.vo;

import java.util.Date;

public class NodeElementMapping {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.MAPPER_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long mapperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.SRC_NODE_DESC_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long srcNodeDescId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.TAR_NODE_DESC_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long tarNodeDescId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.CREATE_TIME
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.TENANT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.POLICY_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private Long policyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_node_element_mapping.STATE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	private String state;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.MAPPER_ID
	 * @return  the value of stl_node_element_mapping.MAPPER_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getMapperId() {
		return mapperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.MAPPER_ID
	 * @param mapperId  the value for stl_node_element_mapping.MAPPER_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setMapperId(Long mapperId) {
		this.mapperId = mapperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.SRC_NODE_DESC_ID
	 * @return  the value of stl_node_element_mapping.SRC_NODE_DESC_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getSrcNodeDescId() {
		return srcNodeDescId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.SRC_NODE_DESC_ID
	 * @param srcNodeDescId  the value for stl_node_element_mapping.SRC_NODE_DESC_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setSrcNodeDescId(Long srcNodeDescId) {
		this.srcNodeDescId = srcNodeDescId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.TAR_NODE_DESC_ID
	 * @return  the value of stl_node_element_mapping.TAR_NODE_DESC_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getTarNodeDescId() {
		return tarNodeDescId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.TAR_NODE_DESC_ID
	 * @param tarNodeDescId  the value for stl_node_element_mapping.TAR_NODE_DESC_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setTarNodeDescId(Long tarNodeDescId) {
		this.tarNodeDescId = tarNodeDescId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.CREATE_TIME
	 * @return  the value of stl_node_element_mapping.CREATE_TIME
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.CREATE_TIME
	 * @param createTime  the value for stl_node_element_mapping.CREATE_TIME
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.TENANT_ID
	 * @return  the value of stl_node_element_mapping.TENANT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.TENANT_ID
	 * @param tenantId  the value for stl_node_element_mapping.TENANT_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.POLICY_ID
	 * @return  the value of stl_node_element_mapping.POLICY_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.POLICY_ID
	 * @param policyId  the value for stl_node_element_mapping.POLICY_ID
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setPolicyId(Long policyId) {
		this.policyId = policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_node_element_mapping.STATE
	 * @return  the value of stl_node_element_mapping.STATE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_node_element_mapping.STATE
	 * @param state  the value for stl_node_element_mapping.STATE
	 * @mbg.generated  Thu Aug 09 16:26:02 CST 2018
	 */
	public void setState(String state) {
		this.state = state;
	}
}