package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.BmcDataquality;
import com.x.ic.msg.dao.mapper.bo.BmcDataqualityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BmcDataqualityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    long countByExample(BmcDataqualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByExample(BmcDataqualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insert(BmcDataquality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insertSelective(BmcDataquality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    List<BmcDataquality> selectByExample(BmcDataqualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") BmcDataquality record, @Param("example") BmcDataqualityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExample(@Param("record") BmcDataquality record, @Param("example") BmcDataqualityExample example);
}