package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.MdsConsumerMapped;
import com.x.ic.msg.dao.mapper.bo.MdsConsumerMappedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MdsConsumerMappedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    long countByExample(MdsConsumerMappedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    int deleteByExample(MdsConsumerMappedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    int insert(MdsConsumerMapped record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    int insertSelective(MdsConsumerMapped record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    List<MdsConsumerMapped> selectByExample(MdsConsumerMappedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") MdsConsumerMapped record, @Param("example") MdsConsumerMappedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    int updateByExample(@Param("record") MdsConsumerMapped record, @Param("example") MdsConsumerMappedExample example);
}