package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlBillStyleItem;
import com.x.ic.msg.dao.mapper.bo.StlBillStyleItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlBillStyleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    long countByExample(StlBillStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByExample(StlBillStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insert(StlBillStyleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insertSelective(StlBillStyleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    List<StlBillStyleItem> selectByExample(StlBillStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    StlBillStyleItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") StlBillStyleItem record, @Param("example") StlBillStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExample(@Param("record") StlBillStyleItem record, @Param("example") StlBillStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByPrimaryKeySelective(StlBillStyleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByPrimaryKey(StlBillStyleItem record);
}