package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlBillDetailStyleItem;
import com.x.ic.msg.dao.mapper.bo.StlBillDetailStyleItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlBillDetailStyleItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    long countByExample(StlBillDetailStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByExample(StlBillDetailStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insert(StlBillDetailStyleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insertSelective(StlBillDetailStyleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    List<StlBillDetailStyleItem> selectByExample(StlBillDetailStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    StlBillDetailStyleItem selectByPrimaryKey(Long itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") StlBillDetailStyleItem record, @Param("example") StlBillDetailStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExample(@Param("record") StlBillDetailStyleItem record, @Param("example") StlBillDetailStyleItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByPrimaryKeySelective(StlBillDetailStyleItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_bill_detail_style_item
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByPrimaryKey(StlBillDetailStyleItem record);
}