package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlElementAttr;
import com.x.ic.msg.dao.mapper.bo.StlElementAttrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlElementAttrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	long countByExample(StlElementAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int deleteByExample(StlElementAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int deleteByPrimaryKey(Long attrId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int insert(StlElementAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int insertSelective(StlElementAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	List<StlElementAttr> selectByExample(StlElementAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	StlElementAttr selectByPrimaryKey(Long attrId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StlElementAttr record,
			@Param("example") StlElementAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int updateByExample(@Param("record") StlElementAttr record, @Param("example") StlElementAttrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int updateByPrimaryKeySelective(StlElementAttr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_element_attr
	 * @mbg.generated  Thu Jul 26 17:27:20 CST 2018
	 */
	int updateByPrimaryKey(StlElementAttr record);
}