package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlPolicyTaskCycle;
import com.x.ic.msg.dao.mapper.bo.StlPolicyTaskCycleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlPolicyTaskCycleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	long countByExample(StlPolicyTaskCycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int deleteByExample(StlPolicyTaskCycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int deleteByPrimaryKey(String policyCycleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int insert(StlPolicyTaskCycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int insertSelective(StlPolicyTaskCycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	List<StlPolicyTaskCycle> selectByExample(StlPolicyTaskCycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	StlPolicyTaskCycle selectByPrimaryKey(String policyCycleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StlPolicyTaskCycle record,
			@Param("example") StlPolicyTaskCycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int updateByExample(@Param("record") StlPolicyTaskCycle record,
			@Param("example") StlPolicyTaskCycleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int updateByPrimaryKeySelective(StlPolicyTaskCycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_task_cycle
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	int updateByPrimaryKey(StlPolicyTaskCycle record);
}