package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlPolicyItemCondition;
import com.x.ic.msg.dao.mapper.bo.StlPolicyItemConditionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlPolicyItemConditionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	long countByExample(StlPolicyItemConditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int deleteByExample(StlPolicyItemConditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int deleteByPrimaryKey(Long conditionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int insert(StlPolicyItemCondition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int insertSelective(StlPolicyItemCondition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	List<StlPolicyItemCondition> selectByExample(StlPolicyItemConditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	StlPolicyItemCondition selectByPrimaryKey(Long conditionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StlPolicyItemCondition record,
			@Param("example") StlPolicyItemConditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int updateByExample(@Param("record") StlPolicyItemCondition record,
			@Param("example") StlPolicyItemConditionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int updateByPrimaryKeySelective(StlPolicyItemCondition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	int updateByPrimaryKey(StlPolicyItemCondition record);
}