package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlPolicyItemPlanInstn;
import com.x.ic.msg.dao.mapper.bo.StlPolicyItemPlanInstnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlPolicyItemPlanInstnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	long countByExample(StlPolicyItemPlanInstnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int deleteByExample(StlPolicyItemPlanInstnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int deleteByPrimaryKey(String policyItemPlanInstnId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int insert(StlPolicyItemPlanInstn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int insertSelective(StlPolicyItemPlanInstn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	List<StlPolicyItemPlanInstn> selectByExample(StlPolicyItemPlanInstnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	StlPolicyItemPlanInstn selectByPrimaryKey(String policyItemPlanInstnId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int updateByExampleSelective(@Param("record") StlPolicyItemPlanInstn record,
			@Param("example") StlPolicyItemPlanInstnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int updateByExample(@Param("record") StlPolicyItemPlanInstn record,
			@Param("example") StlPolicyItemPlanInstnExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int updateByPrimaryKeySelective(StlPolicyItemPlanInstn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_plan_instn
	 * @mbg.generated  Fri Aug 03 16:42:42 CST 2018
	 */
	int updateByPrimaryKey(StlPolicyItemPlanInstn record);
}