package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlPolicyItemPlan;
import com.x.ic.msg.dao.mapper.bo.StlPolicyItemPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlPolicyItemPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    long countByExample(StlPolicyItemPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByExample(StlPolicyItemPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByPrimaryKey(Long planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insert(StlPolicyItemPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insertSelective(StlPolicyItemPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    List<StlPolicyItemPlan> selectByExample(StlPolicyItemPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    StlPolicyItemPlan selectByPrimaryKey(Long planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") StlPolicyItemPlan record, @Param("example") StlPolicyItemPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExample(@Param("record") StlPolicyItemPlan record, @Param("example") StlPolicyItemPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByPrimaryKeySelective(StlPolicyItemPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByPrimaryKey(StlPolicyItemPlan record);
}