package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlPolicyItemPlayInstn;
import com.x.ic.msg.dao.mapper.bo.StlPolicyItemPlayInstnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlPolicyItemPlayInstnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    long countByExample(StlPolicyItemPlayInstnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int deleteByExample(StlPolicyItemPlayInstnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int deleteByPrimaryKey(String policyItemPlanInstnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int insert(StlPolicyItemPlayInstn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int insertSelective(StlPolicyItemPlayInstn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    List<StlPolicyItemPlayInstn> selectByExample(StlPolicyItemPlayInstnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    StlPolicyItemPlayInstn selectByPrimaryKey(String policyItemPlanInstnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") StlPolicyItemPlayInstn record, @Param("example") StlPolicyItemPlayInstnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int updateByExample(@Param("record") StlPolicyItemPlayInstn record, @Param("example") StlPolicyItemPlayInstnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int updateByPrimaryKeySelective(StlPolicyItemPlayInstn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_policy_item_plan_instn
     *
     * @mbg.generated Tue Jul 24 11:29:44 CST 2018
     */
    int updateByPrimaryKey(StlPolicyItemPlayInstn record);
}