package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlSmcMsgLog;
import com.x.ic.msg.dao.mapper.bo.StlSmcMsgLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlSmcMsgLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    long countByExample(StlSmcMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int deleteByExample(StlSmcMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insert(StlSmcMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int insertSelective(StlSmcMsgLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    List<StlSmcMsgLog> selectByExample(StlSmcMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") StlSmcMsgLog record, @Param("example") StlSmcMsgLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_smc_msg_log
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    int updateByExample(@Param("record") StlSmcMsgLog record, @Param("example") StlSmcMsgLogExample example);
}