package com.x.ic.msg.dao.mapper.interfaces;

import com.x.ic.msg.dao.mapper.bo.StlSysParam;
import com.x.ic.msg.dao.mapper.bo.StlSysParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StlSysParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    long countByExample(StlSysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int deleteByExample(StlSysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int deleteByPrimaryKey(String guidkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int insert(StlSysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int insertSelective(StlSysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    List<StlSysParam> selectByExample(StlSysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    StlSysParam selectByPrimaryKey(String guidkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") StlSysParam record, @Param("example") StlSysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int updateByExample(@Param("record") StlSysParam record, @Param("example") StlSysParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int updateByPrimaryKeySelective(StlSysParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stl_sys_param
     *
     * @mbg.generated Tue Jun 12 11:39:06 CST 2018
     */
    int updateByPrimaryKey(StlSysParam record);
}