package com.x.ic.msg.dao.mapper.bo;

public class BmcDataquality {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bmc_dataquality.id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bmc_dataquality.tenant_id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bmc_dataquality.service_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String serviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bmc_dataquality.source
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bmc_dataquality.dup_key
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String dupKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bmc_dataquality.tb_suffix_key
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String tbSuffixKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bmc_dataquality.id
     *
     * @return the value of bmc_dataquality.id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bmc_dataquality.id
     *
     * @param id the value for bmc_dataquality.id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bmc_dataquality.tenant_id
     *
     * @return the value of bmc_dataquality.tenant_id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bmc_dataquality.tenant_id
     *
     * @param tenantId the value for bmc_dataquality.tenant_id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bmc_dataquality.service_type
     *
     * @return the value of bmc_dataquality.service_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bmc_dataquality.service_type
     *
     * @param serviceType the value for bmc_dataquality.service_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bmc_dataquality.source
     *
     * @return the value of bmc_dataquality.source
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bmc_dataquality.source
     *
     * @param source the value for bmc_dataquality.source
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bmc_dataquality.dup_key
     *
     * @return the value of bmc_dataquality.dup_key
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getDupKey() {
        return dupKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bmc_dataquality.dup_key
     *
     * @param dupKey the value for bmc_dataquality.dup_key
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setDupKey(String dupKey) {
        this.dupKey = dupKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bmc_dataquality.tb_suffix_key
     *
     * @return the value of bmc_dataquality.tb_suffix_key
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getTbSuffixKey() {
        return tbSuffixKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bmc_dataquality.tb_suffix_key
     *
     * @param tbSuffixKey the value for bmc_dataquality.tb_suffix_key
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setTbSuffixKey(String tbSuffixKey) {
        this.tbSuffixKey = tbSuffixKey;
    }
}