package com.x.ic.msg.dao.mapper.bo;

import java.util.ArrayList;
import java.util.List;

public class BmcDataqualityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public BmcDataqualityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(String value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(String value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(String value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(String value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(String value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLike(String value) {
            addCriterion("tenant_id like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotLike(String value) {
            addCriterion("tenant_id not like", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<String> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<String> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(String value1, String value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(String value1, String value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNull() {
            addCriterion("service_type is null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNotNull() {
            addCriterion("service_type is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeEqualTo(String value) {
            addCriterion("service_type =", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotEqualTo(String value) {
            addCriterion("service_type <>", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThan(String value) {
            addCriterion("service_type >", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("service_type >=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThan(String value) {
            addCriterion("service_type <", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThanOrEqualTo(String value) {
            addCriterion("service_type <=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLike(String value) {
            addCriterion("service_type like", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotLike(String value) {
            addCriterion("service_type not like", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIn(List<String> values) {
            addCriterion("service_type in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotIn(List<String> values) {
            addCriterion("service_type not in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeBetween(String value1, String value2) {
            addCriterion("service_type between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotBetween(String value1, String value2) {
            addCriterion("service_type not between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andDupKeyIsNull() {
            addCriterion("dup_key is null");
            return (Criteria) this;
        }

        public Criteria andDupKeyIsNotNull() {
            addCriterion("dup_key is not null");
            return (Criteria) this;
        }

        public Criteria andDupKeyEqualTo(String value) {
            addCriterion("dup_key =", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyNotEqualTo(String value) {
            addCriterion("dup_key <>", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyGreaterThan(String value) {
            addCriterion("dup_key >", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyGreaterThanOrEqualTo(String value) {
            addCriterion("dup_key >=", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyLessThan(String value) {
            addCriterion("dup_key <", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyLessThanOrEqualTo(String value) {
            addCriterion("dup_key <=", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyLike(String value) {
            addCriterion("dup_key like", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyNotLike(String value) {
            addCriterion("dup_key not like", value, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyIn(List<String> values) {
            addCriterion("dup_key in", values, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyNotIn(List<String> values) {
            addCriterion("dup_key not in", values, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyBetween(String value1, String value2) {
            addCriterion("dup_key between", value1, value2, "dupKey");
            return (Criteria) this;
        }

        public Criteria andDupKeyNotBetween(String value1, String value2) {
            addCriterion("dup_key not between", value1, value2, "dupKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyIsNull() {
            addCriterion("tb_suffix_key is null");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyIsNotNull() {
            addCriterion("tb_suffix_key is not null");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyEqualTo(String value) {
            addCriterion("tb_suffix_key =", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyNotEqualTo(String value) {
            addCriterion("tb_suffix_key <>", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyGreaterThan(String value) {
            addCriterion("tb_suffix_key >", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyGreaterThanOrEqualTo(String value) {
            addCriterion("tb_suffix_key >=", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyLessThan(String value) {
            addCriterion("tb_suffix_key <", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyLessThanOrEqualTo(String value) {
            addCriterion("tb_suffix_key <=", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyLike(String value) {
            addCriterion("tb_suffix_key like", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyNotLike(String value) {
            addCriterion("tb_suffix_key not like", value, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyIn(List<String> values) {
            addCriterion("tb_suffix_key in", values, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyNotIn(List<String> values) {
            addCriterion("tb_suffix_key not in", values, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyBetween(String value1, String value2) {
            addCriterion("tb_suffix_key between", value1, value2, "tbSuffixKey");
            return (Criteria) this;
        }

        public Criteria andTbSuffixKeyNotBetween(String value1, String value2) {
            addCriterion("tb_suffix_key not between", value1, value2, "tbSuffixKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bmc_dataquality
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 12 14:46:39 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bmc_dataquality
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}