package com.x.ic.msg.dao.mapper.bo;

import java.util.ArrayList;
import java.util.List;

public class MdsConsumerMappedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public MdsConsumerMappedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMdsIdIsNull() {
            addCriterion("MDS_ID is null");
            return (Criteria) this;
        }

        public Criteria andMdsIdIsNotNull() {
            addCriterion("MDS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMdsIdEqualTo(String value) {
            addCriterion("MDS_ID =", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdNotEqualTo(String value) {
            addCriterion("MDS_ID <>", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdGreaterThan(String value) {
            addCriterion("MDS_ID >", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_ID >=", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdLessThan(String value) {
            addCriterion("MDS_ID <", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdLessThanOrEqualTo(String value) {
            addCriterion("MDS_ID <=", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdLike(String value) {
            addCriterion("MDS_ID like", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdNotLike(String value) {
            addCriterion("MDS_ID not like", value, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdIn(List<String> values) {
            addCriterion("MDS_ID in", values, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdNotIn(List<String> values) {
            addCriterion("MDS_ID not in", values, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdBetween(String value1, String value2) {
            addCriterion("MDS_ID between", value1, value2, "mdsId");
            return (Criteria) this;
        }

        public Criteria andMdsIdNotBetween(String value1, String value2) {
            addCriterion("MDS_ID not between", value1, value2, "mdsId");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathIsNull() {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH is null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathIsNotNull() {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH =", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathNotEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH <>", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathGreaterThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH >", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathGreaterThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH >=", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathLessThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH <", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathLessThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH <=", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH like", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathNotLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH not like", value, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH in", values, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathNotIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH not in", values, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH between", value1, value2, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperBrokerPathNotBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_BROKER_PATH not between", value1, value2, "kafkaZookeeperBrokerPath");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsIsNull() {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS is null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsIsNotNull() {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS is not null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS =", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsNotEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS <>", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsGreaterThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS >", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsGreaterThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS >=", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsLessThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS <", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsLessThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS <=", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS like", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsNotLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS not like", value, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS in", values, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsNotIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS not in", values, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS between", value1, value2, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperHostsNotBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_HOSTS not between", value1, value2, "kafkaZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserIsNull() {
            addCriterion("KAFKA_ZOOKEEPER_USER is null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserIsNotNull() {
            addCriterion("KAFKA_ZOOKEEPER_USER is not null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER =", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserNotEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER <>", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserGreaterThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER >", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserGreaterThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER >=", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserLessThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER <", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserLessThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER <=", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER like", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserNotLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER not like", value, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_USER in", values, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserNotIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_USER not in", values, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_USER between", value1, value2, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserNotBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_USER not between", value1, value2, "kafkaZookeeperUser");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdIsNull() {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD is null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdIsNotNull() {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD is not null");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD =", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdNotEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD <>", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdGreaterThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD >", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdGreaterThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD >=", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdLessThan(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD <", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdLessThanOrEqualTo(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD <=", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD like", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdNotLike(String value) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD not like", value, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD in", values, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdNotIn(List<String> values) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD not in", values, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD between", value1, value2, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andKafkaZookeeperUserPasswdNotBetween(String value1, String value2) {
            addCriterion("KAFKA_ZOOKEEPER_USER_PASSWD not between", value1, value2, "kafkaZookeeperUserPasswd");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathIsNull() {
            addCriterion("MDS_CONSUMER_BASE_PATH is null");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathIsNotNull() {
            addCriterion("MDS_CONSUMER_BASE_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathEqualTo(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH =", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathNotEqualTo(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH <>", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathGreaterThan(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH >", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH >=", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathLessThan(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH <", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathLessThanOrEqualTo(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH <=", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathLike(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH like", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathNotLike(String value) {
            addCriterion("MDS_CONSUMER_BASE_PATH not like", value, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathIn(List<String> values) {
            addCriterion("MDS_CONSUMER_BASE_PATH in", values, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathNotIn(List<String> values) {
            addCriterion("MDS_CONSUMER_BASE_PATH not in", values, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathBetween(String value1, String value2) {
            addCriterion("MDS_CONSUMER_BASE_PATH between", value1, value2, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsConsumerBasePathNotBetween(String value1, String value2) {
            addCriterion("MDS_CONSUMER_BASE_PATH not between", value1, value2, "mdsConsumerBasePath");
            return (Criteria) this;
        }

        public Criteria andMdsTopicIsNull() {
            addCriterion("MDS_TOPIC is null");
            return (Criteria) this;
        }

        public Criteria andMdsTopicIsNotNull() {
            addCriterion("MDS_TOPIC is not null");
            return (Criteria) this;
        }

        public Criteria andMdsTopicEqualTo(String value) {
            addCriterion("MDS_TOPIC =", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotEqualTo(String value) {
            addCriterion("MDS_TOPIC <>", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicGreaterThan(String value) {
            addCriterion("MDS_TOPIC >", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_TOPIC >=", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicLessThan(String value) {
            addCriterion("MDS_TOPIC <", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicLessThanOrEqualTo(String value) {
            addCriterion("MDS_TOPIC <=", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicLike(String value) {
            addCriterion("MDS_TOPIC like", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotLike(String value) {
            addCriterion("MDS_TOPIC not like", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicIn(List<String> values) {
            addCriterion("MDS_TOPIC in", values, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotIn(List<String> values) {
            addCriterion("MDS_TOPIC not in", values, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicBetween(String value1, String value2) {
            addCriterion("MDS_TOPIC between", value1, value2, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotBetween(String value1, String value2) {
            addCriterion("MDS_TOPIC not between", value1, value2, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsIsNull() {
            addCriterion("MDS_ZOOKEEPER_HOSTS is null");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsIsNotNull() {
            addCriterion("MDS_ZOOKEEPER_HOSTS is not null");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsEqualTo(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS =", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsNotEqualTo(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS <>", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsGreaterThan(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS >", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS >=", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsLessThan(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS <", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsLessThanOrEqualTo(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS <=", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsLike(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS like", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsNotLike(String value) {
            addCriterion("MDS_ZOOKEEPER_HOSTS not like", value, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsIn(List<String> values) {
            addCriterion("MDS_ZOOKEEPER_HOSTS in", values, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsNotIn(List<String> values) {
            addCriterion("MDS_ZOOKEEPER_HOSTS not in", values, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsBetween(String value1, String value2) {
            addCriterion("MDS_ZOOKEEPER_HOSTS between", value1, value2, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsZookeeperHostsNotBetween(String value1, String value2) {
            addCriterion("MDS_ZOOKEEPER_HOSTS not between", value1, value2, "mdsZookeeperHosts");
            return (Criteria) this;
        }

        public Criteria andMdsTypeIsNull() {
            addCriterion("MDS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMdsTypeIsNotNull() {
            addCriterion("MDS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMdsTypeEqualTo(String value) {
            addCriterion("MDS_TYPE =", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotEqualTo(String value) {
            addCriterion("MDS_TYPE <>", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeGreaterThan(String value) {
            addCriterion("MDS_TYPE >", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_TYPE >=", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeLessThan(String value) {
            addCriterion("MDS_TYPE <", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeLessThanOrEqualTo(String value) {
            addCriterion("MDS_TYPE <=", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeLike(String value) {
            addCriterion("MDS_TYPE like", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotLike(String value) {
            addCriterion("MDS_TYPE not like", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeIn(List<String> values) {
            addCriterion("MDS_TYPE in", values, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotIn(List<String> values) {
            addCriterion("MDS_TYPE not in", values, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeBetween(String value1, String value2) {
            addCriterion("MDS_TYPE between", value1, value2, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotBetween(String value1, String value2) {
            addCriterion("MDS_TYPE not between", value1, value2, "mdsType");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 02 15:48:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MSD_CONSUMER_MAPPED
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}