package com.x.ic.msg.dao.mapper.bo;

public class MdsConsumerMapped {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.MDS_ID
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String mdsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_BROKER_PATH
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String kafkaZookeeperBrokerPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_HOSTS
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String kafkaZookeeperHosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String kafkaZookeeperUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER_PASSWD
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String kafkaZookeeperUserPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.MDS_CONSUMER_BASE_PATH
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String mdsConsumerBasePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.MDS_TOPIC
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String mdsTopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.MDS_ZOOKEEPER_HOSTS
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String mdsZookeeperHosts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.MDS_TYPE
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String mdsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MSD_CONSUMER_MAPPED.STATE
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.MDS_ID
     *
     * @return the value of MSD_CONSUMER_MAPPED.MDS_ID
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getMdsId() {
        return mdsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.MDS_ID
     *
     * @param mdsId the value for MSD_CONSUMER_MAPPED.MDS_ID
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setMdsId(String mdsId) {
        this.mdsId = mdsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_BROKER_PATH
     *
     * @return the value of MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_BROKER_PATH
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getKafkaZookeeperBrokerPath() {
        return kafkaZookeeperBrokerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_BROKER_PATH
     *
     * @param kafkaZookeeperBrokerPath the value for MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_BROKER_PATH
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setKafkaZookeeperBrokerPath(String kafkaZookeeperBrokerPath) {
        this.kafkaZookeeperBrokerPath = kafkaZookeeperBrokerPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_HOSTS
     *
     * @return the value of MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_HOSTS
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getKafkaZookeeperHosts() {
        return kafkaZookeeperHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_HOSTS
     *
     * @param kafkaZookeeperHosts the value for MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_HOSTS
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setKafkaZookeeperHosts(String kafkaZookeeperHosts) {
        this.kafkaZookeeperHosts = kafkaZookeeperHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER
     *
     * @return the value of MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getKafkaZookeeperUser() {
        return kafkaZookeeperUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER
     *
     * @param kafkaZookeeperUser the value for MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setKafkaZookeeperUser(String kafkaZookeeperUser) {
        this.kafkaZookeeperUser = kafkaZookeeperUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER_PASSWD
     *
     * @return the value of MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER_PASSWD
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getKafkaZookeeperUserPasswd() {
        return kafkaZookeeperUserPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER_PASSWD
     *
     * @param kafkaZookeeperUserPasswd the value for MSD_CONSUMER_MAPPED.KAFKA_ZOOKEEPER_USER_PASSWD
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setKafkaZookeeperUserPasswd(String kafkaZookeeperUserPasswd) {
        this.kafkaZookeeperUserPasswd = kafkaZookeeperUserPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.MDS_CONSUMER_BASE_PATH
     *
     * @return the value of MSD_CONSUMER_MAPPED.MDS_CONSUMER_BASE_PATH
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getMdsConsumerBasePath() {
        return mdsConsumerBasePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.MDS_CONSUMER_BASE_PATH
     *
     * @param mdsConsumerBasePath the value for MSD_CONSUMER_MAPPED.MDS_CONSUMER_BASE_PATH
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setMdsConsumerBasePath(String mdsConsumerBasePath) {
        this.mdsConsumerBasePath = mdsConsumerBasePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.MDS_TOPIC
     *
     * @return the value of MSD_CONSUMER_MAPPED.MDS_TOPIC
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getMdsTopic() {
        return mdsTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.MDS_TOPIC
     *
     * @param mdsTopic the value for MSD_CONSUMER_MAPPED.MDS_TOPIC
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setMdsTopic(String mdsTopic) {
        this.mdsTopic = mdsTopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.MDS_ZOOKEEPER_HOSTS
     *
     * @return the value of MSD_CONSUMER_MAPPED.MDS_ZOOKEEPER_HOSTS
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getMdsZookeeperHosts() {
        return mdsZookeeperHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.MDS_ZOOKEEPER_HOSTS
     *
     * @param mdsZookeeperHosts the value for MSD_CONSUMER_MAPPED.MDS_ZOOKEEPER_HOSTS
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setMdsZookeeperHosts(String mdsZookeeperHosts) {
        this.mdsZookeeperHosts = mdsZookeeperHosts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.MDS_TYPE
     *
     * @return the value of MSD_CONSUMER_MAPPED.MDS_TYPE
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getMdsType() {
        return mdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.MDS_TYPE
     *
     * @param mdsType the value for MSD_CONSUMER_MAPPED.MDS_TYPE
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setMdsType(String mdsType) {
        this.mdsType = mdsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MSD_CONSUMER_MAPPED.STATE
     *
     * @return the value of MSD_CONSUMER_MAPPED.STATE
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MSD_CONSUMER_MAPPED.STATE
     *
     * @param state the value for MSD_CONSUMER_MAPPED.STATE
     *
     * @mbg.generated Mon Jul 02 15:48:41 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }
}