package com.x.ic.msg.dao.mapper.bo;

import java.util.ArrayList;
import java.util.List;

public class MdsMappedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public MdsMappedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNsIsNull() {
            addCriterion("NS is null");
            return (Criteria) this;
        }

        public Criteria andNsIsNotNull() {
            addCriterion("NS is not null");
            return (Criteria) this;
        }

        public Criteria andNsEqualTo(String value) {
            addCriterion("NS =", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsNotEqualTo(String value) {
            addCriterion("NS <>", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsGreaterThan(String value) {
            addCriterion("NS >", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsGreaterThanOrEqualTo(String value) {
            addCriterion("NS >=", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsLessThan(String value) {
            addCriterion("NS <", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsLessThanOrEqualTo(String value) {
            addCriterion("NS <=", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsLike(String value) {
            addCriterion("NS like", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsNotLike(String value) {
            addCriterion("NS not like", value, "ns");
            return (Criteria) this;
        }

        public Criteria andNsIn(List<String> values) {
            addCriterion("NS in", values, "ns");
            return (Criteria) this;
        }

        public Criteria andNsNotIn(List<String> values) {
            addCriterion("NS not in", values, "ns");
            return (Criteria) this;
        }

        public Criteria andNsBetween(String value1, String value2) {
            addCriterion("NS between", value1, value2, "ns");
            return (Criteria) this;
        }

        public Criteria andNsNotBetween(String value1, String value2) {
            addCriterion("NS not between", value1, value2, "ns");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesIsNull() {
            addCriterion("BATCH_NUM_MESSAGES is null");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesIsNotNull() {
            addCriterion("BATCH_NUM_MESSAGES is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesEqualTo(String value) {
            addCriterion("BATCH_NUM_MESSAGES =", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesNotEqualTo(String value) {
            addCriterion("BATCH_NUM_MESSAGES <>", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesGreaterThan(String value) {
            addCriterion("BATCH_NUM_MESSAGES >", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesGreaterThanOrEqualTo(String value) {
            addCriterion("BATCH_NUM_MESSAGES >=", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesLessThan(String value) {
            addCriterion("BATCH_NUM_MESSAGES <", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesLessThanOrEqualTo(String value) {
            addCriterion("BATCH_NUM_MESSAGES <=", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesLike(String value) {
            addCriterion("BATCH_NUM_MESSAGES like", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesNotLike(String value) {
            addCriterion("BATCH_NUM_MESSAGES not like", value, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesIn(List<String> values) {
            addCriterion("BATCH_NUM_MESSAGES in", values, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesNotIn(List<String> values) {
            addCriterion("BATCH_NUM_MESSAGES not in", values, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesBetween(String value1, String value2) {
            addCriterion("BATCH_NUM_MESSAGES between", value1, value2, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andBatchNumMessagesNotBetween(String value1, String value2) {
            addCriterion("BATCH_NUM_MESSAGES not between", value1, value2, "batchNumMessages");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecIsNull() {
            addCriterion("COMPRESSION_CODEC is null");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecIsNotNull() {
            addCriterion("COMPRESSION_CODEC is not null");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecEqualTo(String value) {
            addCriterion("COMPRESSION_CODEC =", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecNotEqualTo(String value) {
            addCriterion("COMPRESSION_CODEC <>", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecGreaterThan(String value) {
            addCriterion("COMPRESSION_CODEC >", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecGreaterThanOrEqualTo(String value) {
            addCriterion("COMPRESSION_CODEC >=", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecLessThan(String value) {
            addCriterion("COMPRESSION_CODEC <", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecLessThanOrEqualTo(String value) {
            addCriterion("COMPRESSION_CODEC <=", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecLike(String value) {
            addCriterion("COMPRESSION_CODEC like", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecNotLike(String value) {
            addCriterion("COMPRESSION_CODEC not like", value, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecIn(List<String> values) {
            addCriterion("COMPRESSION_CODEC in", values, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecNotIn(List<String> values) {
            addCriterion("COMPRESSION_CODEC not in", values, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecBetween(String value1, String value2) {
            addCriterion("COMPRESSION_CODEC between", value1, value2, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andCompressionCodecNotBetween(String value1, String value2) {
            addCriterion("COMPRESSION_CODEC not between", value1, value2, "compressionCodec");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassIsNull() {
            addCriterion("KEY_SERIALIZER_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassIsNotNull() {
            addCriterion("KEY_SERIALIZER_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassEqualTo(String value) {
            addCriterion("KEY_SERIALIZER_CLASS =", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassNotEqualTo(String value) {
            addCriterion("KEY_SERIALIZER_CLASS <>", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassGreaterThan(String value) {
            addCriterion("KEY_SERIALIZER_CLASS >", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassGreaterThanOrEqualTo(String value) {
            addCriterion("KEY_SERIALIZER_CLASS >=", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassLessThan(String value) {
            addCriterion("KEY_SERIALIZER_CLASS <", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassLessThanOrEqualTo(String value) {
            addCriterion("KEY_SERIALIZER_CLASS <=", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassLike(String value) {
            addCriterion("KEY_SERIALIZER_CLASS like", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassNotLike(String value) {
            addCriterion("KEY_SERIALIZER_CLASS not like", value, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassIn(List<String> values) {
            addCriterion("KEY_SERIALIZER_CLASS in", values, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassNotIn(List<String> values) {
            addCriterion("KEY_SERIALIZER_CLASS not in", values, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassBetween(String value1, String value2) {
            addCriterion("KEY_SERIALIZER_CLASS between", value1, value2, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andKeySerializerClassNotBetween(String value1, String value2) {
            addCriterion("KEY_SERIALIZER_CLASS not between", value1, value2, "keySerializerClass");
            return (Criteria) this;
        }

        public Criteria andMaxProducerIsNull() {
            addCriterion("MAX_PRODUCER is null");
            return (Criteria) this;
        }

        public Criteria andMaxProducerIsNotNull() {
            addCriterion("MAX_PRODUCER is not null");
            return (Criteria) this;
        }

        public Criteria andMaxProducerEqualTo(String value) {
            addCriterion("MAX_PRODUCER =", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerNotEqualTo(String value) {
            addCriterion("MAX_PRODUCER <>", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerGreaterThan(String value) {
            addCriterion("MAX_PRODUCER >", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerGreaterThanOrEqualTo(String value) {
            addCriterion("MAX_PRODUCER >=", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerLessThan(String value) {
            addCriterion("MAX_PRODUCER <", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerLessThanOrEqualTo(String value) {
            addCriterion("MAX_PRODUCER <=", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerLike(String value) {
            addCriterion("MAX_PRODUCER like", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerNotLike(String value) {
            addCriterion("MAX_PRODUCER not like", value, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerIn(List<String> values) {
            addCriterion("MAX_PRODUCER in", values, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerNotIn(List<String> values) {
            addCriterion("MAX_PRODUCER not in", values, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerBetween(String value1, String value2) {
            addCriterion("MAX_PRODUCER between", value1, value2, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMaxProducerNotBetween(String value1, String value2) {
            addCriterion("MAX_PRODUCER not between", value1, value2, "maxProducer");
            return (Criteria) this;
        }

        public Criteria andMdsTopicIsNull() {
            addCriterion("MDS_TOPIC is null");
            return (Criteria) this;
        }

        public Criteria andMdsTopicIsNotNull() {
            addCriterion("MDS_TOPIC is not null");
            return (Criteria) this;
        }

        public Criteria andMdsTopicEqualTo(String value) {
            addCriterion("MDS_TOPIC =", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotEqualTo(String value) {
            addCriterion("MDS_TOPIC <>", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicGreaterThan(String value) {
            addCriterion("MDS_TOPIC >", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_TOPIC >=", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicLessThan(String value) {
            addCriterion("MDS_TOPIC <", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicLessThanOrEqualTo(String value) {
            addCriterion("MDS_TOPIC <=", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicLike(String value) {
            addCriterion("MDS_TOPIC like", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotLike(String value) {
            addCriterion("MDS_TOPIC not like", value, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicIn(List<String> values) {
            addCriterion("MDS_TOPIC in", values, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotIn(List<String> values) {
            addCriterion("MDS_TOPIC not in", values, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicBetween(String value1, String value2) {
            addCriterion("MDS_TOPIC between", value1, value2, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMdsTopicNotBetween(String value1, String value2) {
            addCriterion("MDS_TOPIC not between", value1, value2, "mdsTopic");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesIsNull() {
            addCriterion("MESSAGE_SEND_MAX_RETRIES is null");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesIsNotNull() {
            addCriterion("MESSAGE_SEND_MAX_RETRIES is not null");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesEqualTo(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES =", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesNotEqualTo(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES <>", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesGreaterThan(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES >", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES >=", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesLessThan(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES <", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES <=", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesLike(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES like", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesNotLike(String value) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES not like", value, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesIn(List<String> values) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES in", values, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesNotIn(List<String> values) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES not in", values, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesBetween(String value1, String value2) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES between", value1, value2, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMessageSendMaxRetriesNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_SEND_MAX_RETRIES not between", value1, value2, "messageSendMaxRetries");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListIsNull() {
            addCriterion("METADATA_BROKER_LIST is null");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListIsNotNull() {
            addCriterion("METADATA_BROKER_LIST is not null");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListEqualTo(String value) {
            addCriterion("METADATA_BROKER_LIST =", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListNotEqualTo(String value) {
            addCriterion("METADATA_BROKER_LIST <>", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListGreaterThan(String value) {
            addCriterion("METADATA_BROKER_LIST >", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListGreaterThanOrEqualTo(String value) {
            addCriterion("METADATA_BROKER_LIST >=", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListLessThan(String value) {
            addCriterion("METADATA_BROKER_LIST <", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListLessThanOrEqualTo(String value) {
            addCriterion("METADATA_BROKER_LIST <=", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListLike(String value) {
            addCriterion("METADATA_BROKER_LIST like", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListNotLike(String value) {
            addCriterion("METADATA_BROKER_LIST not like", value, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListIn(List<String> values) {
            addCriterion("METADATA_BROKER_LIST in", values, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListNotIn(List<String> values) {
            addCriterion("METADATA_BROKER_LIST not in", values, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListBetween(String value1, String value2) {
            addCriterion("METADATA_BROKER_LIST between", value1, value2, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andMetadataBrokerListNotBetween(String value1, String value2) {
            addCriterion("METADATA_BROKER_LIST not between", value1, value2, "metadataBrokerList");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassIsNull() {
            addCriterion("PARTITIONER_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassIsNotNull() {
            addCriterion("PARTITIONER_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassEqualTo(String value) {
            addCriterion("PARTITIONER_CLASS =", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassNotEqualTo(String value) {
            addCriterion("PARTITIONER_CLASS <>", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassGreaterThan(String value) {
            addCriterion("PARTITIONER_CLASS >", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassGreaterThanOrEqualTo(String value) {
            addCriterion("PARTITIONER_CLASS >=", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassLessThan(String value) {
            addCriterion("PARTITIONER_CLASS <", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassLessThanOrEqualTo(String value) {
            addCriterion("PARTITIONER_CLASS <=", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassLike(String value) {
            addCriterion("PARTITIONER_CLASS like", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassNotLike(String value) {
            addCriterion("PARTITIONER_CLASS not like", value, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassIn(List<String> values) {
            addCriterion("PARTITIONER_CLASS in", values, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassNotIn(List<String> values) {
            addCriterion("PARTITIONER_CLASS not in", values, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassBetween(String value1, String value2) {
            addCriterion("PARTITIONER_CLASS between", value1, value2, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andPartitionerClassNotBetween(String value1, String value2) {
            addCriterion("PARTITIONER_CLASS not between", value1, value2, "partitionerClass");
            return (Criteria) this;
        }

        public Criteria andProducerTypeIsNull() {
            addCriterion("PRODUCER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andProducerTypeIsNotNull() {
            addCriterion("PRODUCER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andProducerTypeEqualTo(String value) {
            addCriterion("PRODUCER_TYPE =", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeNotEqualTo(String value) {
            addCriterion("PRODUCER_TYPE <>", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeGreaterThan(String value) {
            addCriterion("PRODUCER_TYPE >", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCER_TYPE >=", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeLessThan(String value) {
            addCriterion("PRODUCER_TYPE <", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCER_TYPE <=", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeLike(String value) {
            addCriterion("PRODUCER_TYPE like", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeNotLike(String value) {
            addCriterion("PRODUCER_TYPE not like", value, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeIn(List<String> values) {
            addCriterion("PRODUCER_TYPE in", values, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeNotIn(List<String> values) {
            addCriterion("PRODUCER_TYPE not in", values, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeBetween(String value1, String value2) {
            addCriterion("PRODUCER_TYPE between", value1, value2, "producerType");
            return (Criteria) this;
        }

        public Criteria andProducerTypeNotBetween(String value1, String value2) {
            addCriterion("PRODUCER_TYPE not between", value1, value2, "producerType");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesIsNull() {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES is null");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesIsNotNull() {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES is not null");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesEqualTo(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES =", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesNotEqualTo(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES <>", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesGreaterThan(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES >", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesGreaterThanOrEqualTo(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES >=", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesLessThan(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES <", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesLessThanOrEqualTo(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES <=", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesLike(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES like", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesNotLike(String value) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES not like", value, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesIn(List<String> values) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES in", values, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesNotIn(List<String> values) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES not in", values, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesBetween(String value1, String value2) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES between", value1, value2, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andQueueBufferingMaxMessagesNotBetween(String value1, String value2) {
            addCriterion("QUEUE_BUFFERING_MAX_MESSAGES not between", value1, value2, "queueBufferingMaxMessages");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksIsNull() {
            addCriterion("REQUEST_REQUIRED_ACKS is null");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksIsNotNull() {
            addCriterion("REQUEST_REQUIRED_ACKS is not null");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksEqualTo(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS =", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksNotEqualTo(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS <>", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksGreaterThan(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS >", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS >=", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksLessThan(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS <", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS <=", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksLike(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS like", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksNotLike(String value) {
            addCriterion("REQUEST_REQUIRED_ACKS not like", value, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksIn(List<String> values) {
            addCriterion("REQUEST_REQUIRED_ACKS in", values, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksNotIn(List<String> values) {
            addCriterion("REQUEST_REQUIRED_ACKS not in", values, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksBetween(String value1, String value2) {
            addCriterion("REQUEST_REQUIRED_ACKS between", value1, value2, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestRequiredAcksNotBetween(String value1, String value2) {
            addCriterion("REQUEST_REQUIRED_ACKS not between", value1, value2, "requestRequiredAcks");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsIsNull() {
            addCriterion("REQUEST_TIMEOUT_MS is null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsIsNotNull() {
            addCriterion("REQUEST_TIMEOUT_MS is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsEqualTo(String value) {
            addCriterion("REQUEST_TIMEOUT_MS =", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsNotEqualTo(String value) {
            addCriterion("REQUEST_TIMEOUT_MS <>", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsGreaterThan(String value) {
            addCriterion("REQUEST_TIMEOUT_MS >", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_TIMEOUT_MS >=", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsLessThan(String value) {
            addCriterion("REQUEST_TIMEOUT_MS <", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_TIMEOUT_MS <=", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsLike(String value) {
            addCriterion("REQUEST_TIMEOUT_MS like", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsNotLike(String value) {
            addCriterion("REQUEST_TIMEOUT_MS not like", value, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsIn(List<String> values) {
            addCriterion("REQUEST_TIMEOUT_MS in", values, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsNotIn(List<String> values) {
            addCriterion("REQUEST_TIMEOUT_MS not in", values, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsBetween(String value1, String value2) {
            addCriterion("REQUEST_TIMEOUT_MS between", value1, value2, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andRequestTimeoutMsNotBetween(String value1, String value2) {
            addCriterion("REQUEST_TIMEOUT_MS not between", value1, value2, "requestTimeoutMs");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesIsNull() {
            addCriterion("SEND_BUFFER_BYTES is null");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesIsNotNull() {
            addCriterion("SEND_BUFFER_BYTES is not null");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesEqualTo(String value) {
            addCriterion("SEND_BUFFER_BYTES =", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesNotEqualTo(String value) {
            addCriterion("SEND_BUFFER_BYTES <>", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesGreaterThan(String value) {
            addCriterion("SEND_BUFFER_BYTES >", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesGreaterThanOrEqualTo(String value) {
            addCriterion("SEND_BUFFER_BYTES >=", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesLessThan(String value) {
            addCriterion("SEND_BUFFER_BYTES <", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesLessThanOrEqualTo(String value) {
            addCriterion("SEND_BUFFER_BYTES <=", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesLike(String value) {
            addCriterion("SEND_BUFFER_BYTES like", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesNotLike(String value) {
            addCriterion("SEND_BUFFER_BYTES not like", value, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesIn(List<String> values) {
            addCriterion("SEND_BUFFER_BYTES in", values, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesNotIn(List<String> values) {
            addCriterion("SEND_BUFFER_BYTES not in", values, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesBetween(String value1, String value2) {
            addCriterion("SEND_BUFFER_BYTES between", value1, value2, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSendBufferBytesNotBetween(String value1, String value2) {
            addCriterion("SEND_BUFFER_BYTES not between", value1, value2, "sendBufferBytes");
            return (Criteria) this;
        }

        public Criteria andSerializerClassIsNull() {
            addCriterion("SERIALIZER_CLASS is null");
            return (Criteria) this;
        }

        public Criteria andSerializerClassIsNotNull() {
            addCriterion("SERIALIZER_CLASS is not null");
            return (Criteria) this;
        }

        public Criteria andSerializerClassEqualTo(String value) {
            addCriterion("SERIALIZER_CLASS =", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassNotEqualTo(String value) {
            addCriterion("SERIALIZER_CLASS <>", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassGreaterThan(String value) {
            addCriterion("SERIALIZER_CLASS >", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassGreaterThanOrEqualTo(String value) {
            addCriterion("SERIALIZER_CLASS >=", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassLessThan(String value) {
            addCriterion("SERIALIZER_CLASS <", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassLessThanOrEqualTo(String value) {
            addCriterion("SERIALIZER_CLASS <=", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassLike(String value) {
            addCriterion("SERIALIZER_CLASS like", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassNotLike(String value) {
            addCriterion("SERIALIZER_CLASS not like", value, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassIn(List<String> values) {
            addCriterion("SERIALIZER_CLASS in", values, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassNotIn(List<String> values) {
            addCriterion("SERIALIZER_CLASS not in", values, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassBetween(String value1, String value2) {
            addCriterion("SERIALIZER_CLASS between", value1, value2, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andSerializerClassNotBetween(String value1, String value2) {
            addCriterion("SERIALIZER_CLASS not between", value1, value2, "serializerClass");
            return (Criteria) this;
        }

        public Criteria andMdsTypeIsNull() {
            addCriterion("MDS_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andMdsTypeIsNotNull() {
            addCriterion("MDS_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andMdsTypeEqualTo(String value) {
            addCriterion("MDS_TYPE =", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotEqualTo(String value) {
            addCriterion("MDS_TYPE <>", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeGreaterThan(String value) {
            addCriterion("MDS_TYPE >", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MDS_TYPE >=", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeLessThan(String value) {
            addCriterion("MDS_TYPE <", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeLessThanOrEqualTo(String value) {
            addCriterion("MDS_TYPE <=", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeLike(String value) {
            addCriterion("MDS_TYPE like", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotLike(String value) {
            addCriterion("MDS_TYPE not like", value, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeIn(List<String> values) {
            addCriterion("MDS_TYPE in", values, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotIn(List<String> values) {
            addCriterion("MDS_TYPE not in", values, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeBetween(String value1, String value2) {
            addCriterion("MDS_TYPE between", value1, value2, "mdsType");
            return (Criteria) this;
        }

        public Criteria andMdsTypeNotBetween(String value1, String value2) {
            addCriterion("MDS_TYPE not between", value1, value2, "mdsType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mds_mapped
     *
     * @mbg.generated do_not_delete_during_merge Tue Jun 26 14:20:56 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mds_mapped
     *
     * @mbg.generated Tue Jun 26 14:20:56 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}