package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlBillDetailStyleItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.ITEM_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.BILL_STYLE_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long billStyleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.ITEM_CODE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String itemCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.ITEM_TITLE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String itemTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.ITEM_OWNER
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String itemOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.CHECK_FLAG
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String checkFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.OBJECT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.ELEMENT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long elementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.SORT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Integer sortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.IS_SPLIT_ITEM
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String isSplitItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.CREATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String createDeptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.CREATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String createOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String updateDeptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String updateOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_detail_style_item.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.ITEM_ID
     *
     * @return the value of stl_bill_detail_style_item.ITEM_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.ITEM_ID
     *
     * @param itemId the value for stl_bill_detail_style_item.ITEM_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.BILL_STYLE_ID
     *
     * @return the value of stl_bill_detail_style_item.BILL_STYLE_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getBillStyleId() {
        return billStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.BILL_STYLE_ID
     *
     * @param billStyleId the value for stl_bill_detail_style_item.BILL_STYLE_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setBillStyleId(Long billStyleId) {
        this.billStyleId = billStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.TENANT_ID
     *
     * @return the value of stl_bill_detail_style_item.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.TENANT_ID
     *
     * @param tenantId the value for stl_bill_detail_style_item.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.ITEM_CODE
     *
     * @return the value of stl_bill_detail_style_item.ITEM_CODE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.ITEM_CODE
     *
     * @param itemCode the value for stl_bill_detail_style_item.ITEM_CODE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.ITEM_TITLE
     *
     * @return the value of stl_bill_detail_style_item.ITEM_TITLE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getItemTitle() {
        return itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.ITEM_TITLE
     *
     * @param itemTitle the value for stl_bill_detail_style_item.ITEM_TITLE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setItemTitle(String itemTitle) {
        this.itemTitle = itemTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.ITEM_OWNER
     *
     * @return the value of stl_bill_detail_style_item.ITEM_OWNER
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getItemOwner() {
        return itemOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.ITEM_OWNER
     *
     * @param itemOwner the value for stl_bill_detail_style_item.ITEM_OWNER
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setItemOwner(String itemOwner) {
        this.itemOwner = itemOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.CHECK_FLAG
     *
     * @return the value of stl_bill_detail_style_item.CHECK_FLAG
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCheckFlag() {
        return checkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.CHECK_FLAG
     *
     * @param checkFlag the value for stl_bill_detail_style_item.CHECK_FLAG
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCheckFlag(String checkFlag) {
        this.checkFlag = checkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.OBJECT_ID
     *
     * @return the value of stl_bill_detail_style_item.OBJECT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.OBJECT_ID
     *
     * @param objectId the value for stl_bill_detail_style_item.OBJECT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.ELEMENT_ID
     *
     * @return the value of stl_bill_detail_style_item.ELEMENT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.ELEMENT_ID
     *
     * @param elementId the value for stl_bill_detail_style_item.ELEMENT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setElementId(Long elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.SORT_ID
     *
     * @return the value of stl_bill_detail_style_item.SORT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.SORT_ID
     *
     * @param sortId the value for stl_bill_detail_style_item.SORT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.IS_SPLIT_ITEM
     *
     * @return the value of stl_bill_detail_style_item.IS_SPLIT_ITEM
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getIsSplitItem() {
        return isSplitItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.IS_SPLIT_ITEM
     *
     * @param isSplitItem the value for stl_bill_detail_style_item.IS_SPLIT_ITEM
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setIsSplitItem(String isSplitItem) {
        this.isSplitItem = isSplitItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.CREATE_DEPT_ID
     *
     * @return the value of stl_bill_detail_style_item.CREATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCreateDeptId() {
        return createDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.CREATE_DEPT_ID
     *
     * @param createDeptId the value for stl_bill_detail_style_item.CREATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.CREATE_OPER_ID
     *
     * @return the value of stl_bill_detail_style_item.CREATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCreateOperId() {
        return createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.CREATE_OPER_ID
     *
     * @param createOperId the value for stl_bill_detail_style_item.CREATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCreateOperId(String createOperId) {
        this.createOperId = createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.CREATE_TIME
     *
     * @return the value of stl_bill_detail_style_item.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.CREATE_TIME
     *
     * @param createTime the value for stl_bill_detail_style_item.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.UPDATE_DEPT_ID
     *
     * @return the value of stl_bill_detail_style_item.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getUpdateDeptId() {
        return updateDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.UPDATE_DEPT_ID
     *
     * @param updateDeptId the value for stl_bill_detail_style_item.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateDeptId(String updateDeptId) {
        this.updateDeptId = updateDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.UPDATE_OPER_ID
     *
     * @return the value of stl_bill_detail_style_item.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getUpdateOperId() {
        return updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.UPDATE_OPER_ID
     *
     * @param updateOperId the value for stl_bill_detail_style_item.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateOperId(String updateOperId) {
        this.updateOperId = updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_detail_style_item.UPDATE_TIME
     *
     * @return the value of stl_bill_detail_style_item.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_detail_style_item.UPDATE_TIME
     *
     * @param updateTime the value for stl_bill_detail_style_item.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}