package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlBillStyle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.BILL_STYLE_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long billStyleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.BILL_STYLE_SN
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String billStyleSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.BILL_TITLE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String billTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.STATE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.CREATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String createDeptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.CREATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String createOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String updateDeptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String updateOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_bill_style.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.BILL_STYLE_ID
     *
     * @return the value of stl_bill_style.BILL_STYLE_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getBillStyleId() {
        return billStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.BILL_STYLE_ID
     *
     * @param billStyleId the value for stl_bill_style.BILL_STYLE_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setBillStyleId(Long billStyleId) {
        this.billStyleId = billStyleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.TENANT_ID
     *
     * @return the value of stl_bill_style.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.TENANT_ID
     *
     * @param tenantId the value for stl_bill_style.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.BILL_STYLE_SN
     *
     * @return the value of stl_bill_style.BILL_STYLE_SN
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getBillStyleSn() {
        return billStyleSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.BILL_STYLE_SN
     *
     * @param billStyleSn the value for stl_bill_style.BILL_STYLE_SN
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setBillStyleSn(String billStyleSn) {
        this.billStyleSn = billStyleSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.BILL_TITLE
     *
     * @return the value of stl_bill_style.BILL_TITLE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getBillTitle() {
        return billTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.BILL_TITLE
     *
     * @param billTitle the value for stl_bill_style.BILL_TITLE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setBillTitle(String billTitle) {
        this.billTitle = billTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.STATE
     *
     * @return the value of stl_bill_style.STATE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.STATE
     *
     * @param state the value for stl_bill_style.STATE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.CREATE_DEPT_ID
     *
     * @return the value of stl_bill_style.CREATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCreateDeptId() {
        return createDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.CREATE_DEPT_ID
     *
     * @param createDeptId the value for stl_bill_style.CREATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCreateDeptId(String createDeptId) {
        this.createDeptId = createDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.CREATE_OPER_ID
     *
     * @return the value of stl_bill_style.CREATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCreateOperId() {
        return createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.CREATE_OPER_ID
     *
     * @param createOperId the value for stl_bill_style.CREATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCreateOperId(String createOperId) {
        this.createOperId = createOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.CREATE_TIME
     *
     * @return the value of stl_bill_style.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.CREATE_TIME
     *
     * @param createTime the value for stl_bill_style.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.UPDATE_DEPT_ID
     *
     * @return the value of stl_bill_style.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getUpdateDeptId() {
        return updateDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.UPDATE_DEPT_ID
     *
     * @param updateDeptId the value for stl_bill_style.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateDeptId(String updateDeptId) {
        this.updateDeptId = updateDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.UPDATE_OPER_ID
     *
     * @return the value of stl_bill_style.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getUpdateOperId() {
        return updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.UPDATE_OPER_ID
     *
     * @param updateOperId the value for stl_bill_style.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateOperId(String updateOperId) {
        this.updateOperId = updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_bill_style.UPDATE_TIME
     *
     * @return the value of stl_bill_style.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_bill_style.UPDATE_TIME
     *
     * @param updateTime the value for stl_bill_style.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}