package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlElement {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.ELEMENT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private Long elementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.TENANT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.ELEMENT_CODE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String elementCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.ELEMENT_NAME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String elementName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.OBJECT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.ATTR_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String attrType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.IS_SETTLEMENT
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String isSettlement;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.VALUE_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String valueType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.IS_NECESSARY
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String isNecessary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.ELEMENT_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String elementType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.DATA_CREATE_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String dataCreateType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.IS_PRIMARY_KEY
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String isPrimaryKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.UNIT
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String unit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.SORT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private Integer sortId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.ELEMENT_DESC
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String elementDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.STATISTICS_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String statisticsType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.STATISTICS_CYC
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String statisticsCyc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.STATISTICS_OBJECT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String statisticsObjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.STATISTICS_ELEMENT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private Long statisticsElementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.STATE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.CREATE_DEPT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String createDeptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.CREATE_OPER_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String createOperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.CREATE_TIME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.UPDATE_DEPT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String updateDeptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.UPDATE_OPER_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private String updateOperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.UPDATE_TIME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_element.POLICY_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	private Long policyId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.ELEMENT_ID
	 * @return  the value of stl_element.ELEMENT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public Long getElementId() {
		return elementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.ELEMENT_ID
	 * @param elementId  the value for stl_element.ELEMENT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setElementId(Long elementId) {
		this.elementId = elementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.TENANT_ID
	 * @return  the value of stl_element.TENANT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.TENANT_ID
	 * @param tenantId  the value for stl_element.TENANT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.ELEMENT_CODE
	 * @return  the value of stl_element.ELEMENT_CODE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getElementCode() {
		return elementCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.ELEMENT_CODE
	 * @param elementCode  the value for stl_element.ELEMENT_CODE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setElementCode(String elementCode) {
		this.elementCode = elementCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.ELEMENT_NAME
	 * @return  the value of stl_element.ELEMENT_NAME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getElementName() {
		return elementName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.ELEMENT_NAME
	 * @param elementName  the value for stl_element.ELEMENT_NAME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.OBJECT_ID
	 * @return  the value of stl_element.OBJECT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.OBJECT_ID
	 * @param objectId  the value for stl_element.OBJECT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.ATTR_TYPE
	 * @return  the value of stl_element.ATTR_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getAttrType() {
		return attrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.ATTR_TYPE
	 * @param attrType  the value for stl_element.ATTR_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setAttrType(String attrType) {
		this.attrType = attrType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.IS_SETTLEMENT
	 * @return  the value of stl_element.IS_SETTLEMENT
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getIsSettlement() {
		return isSettlement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.IS_SETTLEMENT
	 * @param isSettlement  the value for stl_element.IS_SETTLEMENT
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setIsSettlement(String isSettlement) {
		this.isSettlement = isSettlement;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.VALUE_TYPE
	 * @return  the value of stl_element.VALUE_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getValueType() {
		return valueType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.VALUE_TYPE
	 * @param valueType  the value for stl_element.VALUE_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.IS_NECESSARY
	 * @return  the value of stl_element.IS_NECESSARY
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getIsNecessary() {
		return isNecessary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.IS_NECESSARY
	 * @param isNecessary  the value for stl_element.IS_NECESSARY
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setIsNecessary(String isNecessary) {
		this.isNecessary = isNecessary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.ELEMENT_TYPE
	 * @return  the value of stl_element.ELEMENT_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getElementType() {
		return elementType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.ELEMENT_TYPE
	 * @param elementType  the value for stl_element.ELEMENT_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setElementType(String elementType) {
		this.elementType = elementType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.DATA_CREATE_TYPE
	 * @return  the value of stl_element.DATA_CREATE_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getDataCreateType() {
		return dataCreateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.DATA_CREATE_TYPE
	 * @param dataCreateType  the value for stl_element.DATA_CREATE_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setDataCreateType(String dataCreateType) {
		this.dataCreateType = dataCreateType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.IS_PRIMARY_KEY
	 * @return  the value of stl_element.IS_PRIMARY_KEY
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getIsPrimaryKey() {
		return isPrimaryKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.IS_PRIMARY_KEY
	 * @param isPrimaryKey  the value for stl_element.IS_PRIMARY_KEY
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setIsPrimaryKey(String isPrimaryKey) {
		this.isPrimaryKey = isPrimaryKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.UNIT
	 * @return  the value of stl_element.UNIT
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.UNIT
	 * @param unit  the value for stl_element.UNIT
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.SORT_ID
	 * @return  the value of stl_element.SORT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public Integer getSortId() {
		return sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.SORT_ID
	 * @param sortId  the value for stl_element.SORT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setSortId(Integer sortId) {
		this.sortId = sortId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.ELEMENT_DESC
	 * @return  the value of stl_element.ELEMENT_DESC
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getElementDesc() {
		return elementDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.ELEMENT_DESC
	 * @param elementDesc  the value for stl_element.ELEMENT_DESC
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setElementDesc(String elementDesc) {
		this.elementDesc = elementDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.STATISTICS_TYPE
	 * @return  the value of stl_element.STATISTICS_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getStatisticsType() {
		return statisticsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.STATISTICS_TYPE
	 * @param statisticsType  the value for stl_element.STATISTICS_TYPE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setStatisticsType(String statisticsType) {
		this.statisticsType = statisticsType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.STATISTICS_CYC
	 * @return  the value of stl_element.STATISTICS_CYC
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getStatisticsCyc() {
		return statisticsCyc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.STATISTICS_CYC
	 * @param statisticsCyc  the value for stl_element.STATISTICS_CYC
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setStatisticsCyc(String statisticsCyc) {
		this.statisticsCyc = statisticsCyc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.STATISTICS_OBJECT_ID
	 * @return  the value of stl_element.STATISTICS_OBJECT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getStatisticsObjectId() {
		return statisticsObjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.STATISTICS_OBJECT_ID
	 * @param statisticsObjectId  the value for stl_element.STATISTICS_OBJECT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setStatisticsObjectId(String statisticsObjectId) {
		this.statisticsObjectId = statisticsObjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.STATISTICS_ELEMENT_ID
	 * @return  the value of stl_element.STATISTICS_ELEMENT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public Long getStatisticsElementId() {
		return statisticsElementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.STATISTICS_ELEMENT_ID
	 * @param statisticsElementId  the value for stl_element.STATISTICS_ELEMENT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setStatisticsElementId(Long statisticsElementId) {
		this.statisticsElementId = statisticsElementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.STATE
	 * @return  the value of stl_element.STATE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.STATE
	 * @param state  the value for stl_element.STATE
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.CREATE_DEPT_ID
	 * @return  the value of stl_element.CREATE_DEPT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getCreateDeptId() {
		return createDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.CREATE_DEPT_ID
	 * @param createDeptId  the value for stl_element.CREATE_DEPT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setCreateDeptId(String createDeptId) {
		this.createDeptId = createDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.CREATE_OPER_ID
	 * @return  the value of stl_element.CREATE_OPER_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getCreateOperId() {
		return createOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.CREATE_OPER_ID
	 * @param createOperId  the value for stl_element.CREATE_OPER_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setCreateOperId(String createOperId) {
		this.createOperId = createOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.CREATE_TIME
	 * @return  the value of stl_element.CREATE_TIME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.CREATE_TIME
	 * @param createTime  the value for stl_element.CREATE_TIME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.UPDATE_DEPT_ID
	 * @return  the value of stl_element.UPDATE_DEPT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getUpdateDeptId() {
		return updateDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.UPDATE_DEPT_ID
	 * @param updateDeptId  the value for stl_element.UPDATE_DEPT_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setUpdateDeptId(String updateDeptId) {
		this.updateDeptId = updateDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.UPDATE_OPER_ID
	 * @return  the value of stl_element.UPDATE_OPER_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public String getUpdateOperId() {
		return updateOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.UPDATE_OPER_ID
	 * @param updateOperId  the value for stl_element.UPDATE_OPER_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setUpdateOperId(String updateOperId) {
		this.updateOperId = updateOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.UPDATE_TIME
	 * @return  the value of stl_element.UPDATE_TIME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.UPDATE_TIME
	 * @param updateTime  the value for stl_element.UPDATE_TIME
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_element.POLICY_ID
	 * @return  the value of stl_element.POLICY_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_element.POLICY_ID
	 * @param policyId  the value for stl_element.POLICY_ID
	 * @mbg.generated  Tue Jul 03 15:25:40 CST 2018
	 */
	public void setPolicyId(Long policyId) {
		this.policyId = policyId;
	}
}