package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlNode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.NODE_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private Long nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.NODE_NAME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.NODE_CODE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String nodeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.PARENT_NODE_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private Long parentNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.NODE_PATH
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String nodePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.NODE_TYPE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String nodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.IS_NEED_CHECK
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String isNeedCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.STATE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.LASTEST_TIME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private Date lastestTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.DESCRIPTION
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_node.CONTRACT_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    private String contractId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.NODE_ID
     *
     * @return the value of stl_node.NODE_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.NODE_ID
     *
     * @param nodeId the value for stl_node.NODE_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.NODE_NAME
     *
     * @return the value of stl_node.NODE_NAME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.NODE_NAME
     *
     * @param nodeName the value for stl_node.NODE_NAME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.NODE_CODE
     *
     * @return the value of stl_node.NODE_CODE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getNodeCode() {
        return nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.NODE_CODE
     *
     * @param nodeCode the value for stl_node.NODE_CODE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.PARENT_NODE_ID
     *
     * @return the value of stl_node.PARENT_NODE_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public Long getParentNodeId() {
        return parentNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.PARENT_NODE_ID
     *
     * @param parentNodeId the value for stl_node.PARENT_NODE_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setParentNodeId(Long parentNodeId) {
        this.parentNodeId = parentNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.NODE_PATH
     *
     * @return the value of stl_node.NODE_PATH
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getNodePath() {
        return nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.NODE_PATH
     *
     * @param nodePath the value for stl_node.NODE_PATH
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setNodePath(String nodePath) {
        this.nodePath = nodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.NODE_TYPE
     *
     * @return the value of stl_node.NODE_TYPE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.NODE_TYPE
     *
     * @param nodeType the value for stl_node.NODE_TYPE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.IS_NEED_CHECK
     *
     * @return the value of stl_node.IS_NEED_CHECK
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getIsNeedCheck() {
        return isNeedCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.IS_NEED_CHECK
     *
     * @param isNeedCheck the value for stl_node.IS_NEED_CHECK
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setIsNeedCheck(String isNeedCheck) {
        this.isNeedCheck = isNeedCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.STATE
     *
     * @return the value of stl_node.STATE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.STATE
     *
     * @param state the value for stl_node.STATE
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.CREATE_TIME
     *
     * @return the value of stl_node.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.CREATE_TIME
     *
     * @param createTime the value for stl_node.CREATE_TIME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.LASTEST_TIME
     *
     * @return the value of stl_node.LASTEST_TIME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public Date getLastestTime() {
        return lastestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.LASTEST_TIME
     *
     * @param lastestTime the value for stl_node.LASTEST_TIME
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setLastestTime(Date lastestTime) {
        this.lastestTime = lastestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.DESCRIPTION
     *
     * @return the value of stl_node.DESCRIPTION
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.DESCRIPTION
     *
     * @param description the value for stl_node.DESCRIPTION
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.TENANT_ID
     *
     * @return the value of stl_node.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.TENANT_ID
     *
     * @param tenantId the value for stl_node.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_node.CONTRACT_ID
     *
     * @return the value of stl_node.CONTRACT_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_node.CONTRACT_ID
     *
     * @param contractId the value for stl_node.CONTRACT_ID
     *
     * @mbg.generated Tue Jun 12 18:41:50 CST 2018
     */
    public void setContractId(String contractId) {
        this.contractId = contractId;
    }
}