package com.x.ic.msg.dao.mapper.bo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StlPolicyInstnExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public StlPolicyInstnExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPolicyInstnIdIsNull() {
			addCriterion("POLICY_INSTN_ID is null");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdIsNotNull() {
			addCriterion("POLICY_INSTN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdEqualTo(String value) {
			addCriterion("POLICY_INSTN_ID =", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdNotEqualTo(String value) {
			addCriterion("POLICY_INSTN_ID <>", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdGreaterThan(String value) {
			addCriterion("POLICY_INSTN_ID >", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdGreaterThanOrEqualTo(String value) {
			addCriterion("POLICY_INSTN_ID >=", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdLessThan(String value) {
			addCriterion("POLICY_INSTN_ID <", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdLessThanOrEqualTo(String value) {
			addCriterion("POLICY_INSTN_ID <=", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdLike(String value) {
			addCriterion("POLICY_INSTN_ID like", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdNotLike(String value) {
			addCriterion("POLICY_INSTN_ID not like", value, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdIn(List<String> values) {
			addCriterion("POLICY_INSTN_ID in", values, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdNotIn(List<String> values) {
			addCriterion("POLICY_INSTN_ID not in", values, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdBetween(String value1, String value2) {
			addCriterion("POLICY_INSTN_ID between", value1, value2, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andPolicyInstnIdNotBetween(String value1, String value2) {
			addCriterion("POLICY_INSTN_ID not between", value1, value2, "policyInstnId");
			return (Criteria) this;
		}

		public Criteria andInstnTypeIsNull() {
			addCriterion("INSTN_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andInstnTypeIsNotNull() {
			addCriterion("INSTN_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andInstnTypeEqualTo(String value) {
			addCriterion("INSTN_TYPE =", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeNotEqualTo(String value) {
			addCriterion("INSTN_TYPE <>", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeGreaterThan(String value) {
			addCriterion("INSTN_TYPE >", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeGreaterThanOrEqualTo(String value) {
			addCriterion("INSTN_TYPE >=", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeLessThan(String value) {
			addCriterion("INSTN_TYPE <", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeLessThanOrEqualTo(String value) {
			addCriterion("INSTN_TYPE <=", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeLike(String value) {
			addCriterion("INSTN_TYPE like", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeNotLike(String value) {
			addCriterion("INSTN_TYPE not like", value, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeIn(List<String> values) {
			addCriterion("INSTN_TYPE in", values, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeNotIn(List<String> values) {
			addCriterion("INSTN_TYPE not in", values, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeBetween(String value1, String value2) {
			addCriterion("INSTN_TYPE between", value1, value2, "instnType");
			return (Criteria) this;
		}

		public Criteria andInstnTypeNotBetween(String value1, String value2) {
			addCriterion("INSTN_TYPE not between", value1, value2, "instnType");
			return (Criteria) this;
		}

		public Criteria andObjectCodeIsNull() {
			addCriterion("OBJECT_CODE is null");
			return (Criteria) this;
		}

		public Criteria andObjectCodeIsNotNull() {
			addCriterion("OBJECT_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andObjectCodeEqualTo(String value) {
			addCriterion("OBJECT_CODE =", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeNotEqualTo(String value) {
			addCriterion("OBJECT_CODE <>", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeGreaterThan(String value) {
			addCriterion("OBJECT_CODE >", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeGreaterThanOrEqualTo(String value) {
			addCriterion("OBJECT_CODE >=", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeLessThan(String value) {
			addCriterion("OBJECT_CODE <", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeLessThanOrEqualTo(String value) {
			addCriterion("OBJECT_CODE <=", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeLike(String value) {
			addCriterion("OBJECT_CODE like", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeNotLike(String value) {
			addCriterion("OBJECT_CODE not like", value, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeIn(List<String> values) {
			addCriterion("OBJECT_CODE in", values, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeNotIn(List<String> values) {
			addCriterion("OBJECT_CODE not in", values, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeBetween(String value1, String value2) {
			addCriterion("OBJECT_CODE between", value1, value2, "objectCode");
			return (Criteria) this;
		}

		public Criteria andObjectCodeNotBetween(String value1, String value2) {
			addCriterion("OBJECT_CODE not between", value1, value2, "objectCode");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("START_TIME is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("START_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Date value) {
			addCriterion("START_TIME =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Date value) {
			addCriterion("START_TIME <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Date value) {
			addCriterion("START_TIME >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("START_TIME >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Date value) {
			addCriterion("START_TIME <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("START_TIME <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Date> values) {
			addCriterion("START_TIME in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Date> values) {
			addCriterion("START_TIME not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Date value1, Date value2) {
			addCriterion("START_TIME between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("START_TIME not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("END_TIME is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("END_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterion("END_TIME =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterion("END_TIME <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterion("END_TIME >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("END_TIME >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterion("END_TIME <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterion("END_TIME <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterion("END_TIME in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterion("END_TIME not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterion("END_TIME between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterion("END_TIME not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("TENANT_ID is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("TENANT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(String value) {
			addCriterion("TENANT_ID =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(String value) {
			addCriterion("TENANT_ID <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(String value) {
			addCriterion("TENANT_ID >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
			addCriterion("TENANT_ID >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(String value) {
			addCriterion("TENANT_ID <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(String value) {
			addCriterion("TENANT_ID <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLike(String value) {
			addCriterion("TENANT_ID like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotLike(String value) {
			addCriterion("TENANT_ID not like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<String> values) {
			addCriterion("TENANT_ID in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<String> values) {
			addCriterion("TENANT_ID not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(String value1, String value2) {
			addCriterion("TENANT_ID between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(String value1, String value2) {
			addCriterion("TENANT_ID not between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("CREATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("CREATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("CREATE_DATE =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("CREATE_DATE <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("CREATE_DATE >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("CREATE_DATE <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_DATE <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("CREATE_DATE in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("CREATE_DATE not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_DATE not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdIsNull() {
			addCriterion("CREATE_STAFF_ID is null");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdIsNotNull() {
			addCriterion("CREATE_STAFF_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdEqualTo(String value) {
			addCriterion("CREATE_STAFF_ID =", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdNotEqualTo(String value) {
			addCriterion("CREATE_STAFF_ID <>", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdGreaterThan(String value) {
			addCriterion("CREATE_STAFF_ID >", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdGreaterThanOrEqualTo(String value) {
			addCriterion("CREATE_STAFF_ID >=", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdLessThan(String value) {
			addCriterion("CREATE_STAFF_ID <", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdLessThanOrEqualTo(String value) {
			addCriterion("CREATE_STAFF_ID <=", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdLike(String value) {
			addCriterion("CREATE_STAFF_ID like", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdNotLike(String value) {
			addCriterion("CREATE_STAFF_ID not like", value, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdIn(List<String> values) {
			addCriterion("CREATE_STAFF_ID in", values, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdNotIn(List<String> values) {
			addCriterion("CREATE_STAFF_ID not in", values, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdBetween(String value1, String value2) {
			addCriterion("CREATE_STAFF_ID between", value1, value2, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andCreateStaffIdNotBetween(String value1, String value2) {
			addCriterion("CREATE_STAFF_ID not between", value1, value2, "createStaffId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdIsNull() {
			addCriterion("POLICY_ID is null");
			return (Criteria) this;
		}

		public Criteria andPolicyIdIsNotNull() {
			addCriterion("POLICY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPolicyIdEqualTo(Long value) {
			addCriterion("POLICY_ID =", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdNotEqualTo(Long value) {
			addCriterion("POLICY_ID <>", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdGreaterThan(Long value) {
			addCriterion("POLICY_ID >", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("POLICY_ID >=", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdLessThan(Long value) {
			addCriterion("POLICY_ID <", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdLessThanOrEqualTo(Long value) {
			addCriterion("POLICY_ID <=", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdIn(List<Long> values) {
			addCriterion("POLICY_ID in", values, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdNotIn(List<Long> values) {
			addCriterion("POLICY_ID not in", values, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdBetween(Long value1, Long value2) {
			addCriterion("POLICY_ID between", value1, value2, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdNotBetween(Long value1, Long value2) {
			addCriterion("POLICY_ID not between", value1, value2, "policyId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stl_policy_instn
	 * @mbg.generated  Thu Aug 09 16:29:18 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stl_policy_instn
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 13 10:42:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}