package com.x.ic.msg.dao.mapper.bo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StlPolicyItemConditionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public StlPolicyItemConditionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andConditionIdIsNull() {
			addCriterion("CONDITION_ID is null");
			return (Criteria) this;
		}

		public Criteria andConditionIdIsNotNull() {
			addCriterion("CONDITION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andConditionIdEqualTo(Long value) {
			addCriterion("CONDITION_ID =", value, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdNotEqualTo(Long value) {
			addCriterion("CONDITION_ID <>", value, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdGreaterThan(Long value) {
			addCriterion("CONDITION_ID >", value, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdGreaterThanOrEqualTo(Long value) {
			addCriterion("CONDITION_ID >=", value, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdLessThan(Long value) {
			addCriterion("CONDITION_ID <", value, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdLessThanOrEqualTo(Long value) {
			addCriterion("CONDITION_ID <=", value, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdIn(List<Long> values) {
			addCriterion("CONDITION_ID in", values, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdNotIn(List<Long> values) {
			addCriterion("CONDITION_ID not in", values, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdBetween(Long value1, Long value2) {
			addCriterion("CONDITION_ID between", value1, value2, "conditionId");
			return (Criteria) this;
		}

		public Criteria andConditionIdNotBetween(Long value1, Long value2) {
			addCriterion("CONDITION_ID not between", value1, value2, "conditionId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNull() {
			addCriterion("TENANT_ID is null");
			return (Criteria) this;
		}

		public Criteria andTenantIdIsNotNull() {
			addCriterion("TENANT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andTenantIdEqualTo(String value) {
			addCriterion("TENANT_ID =", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotEqualTo(String value) {
			addCriterion("TENANT_ID <>", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThan(String value) {
			addCriterion("TENANT_ID >", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdGreaterThanOrEqualTo(String value) {
			addCriterion("TENANT_ID >=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThan(String value) {
			addCriterion("TENANT_ID <", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLessThanOrEqualTo(String value) {
			addCriterion("TENANT_ID <=", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdLike(String value) {
			addCriterion("TENANT_ID like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotLike(String value) {
			addCriterion("TENANT_ID not like", value, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdIn(List<String> values) {
			addCriterion("TENANT_ID in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotIn(List<String> values) {
			addCriterion("TENANT_ID not in", values, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdBetween(String value1, String value2) {
			addCriterion("TENANT_ID between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andTenantIdNotBetween(String value1, String value2) {
			addCriterion("TENANT_ID not between", value1, value2, "tenantId");
			return (Criteria) this;
		}

		public Criteria andItemIdIsNull() {
			addCriterion("ITEM_ID is null");
			return (Criteria) this;
		}

		public Criteria andItemIdIsNotNull() {
			addCriterion("ITEM_ID is not null");
			return (Criteria) this;
		}

		public Criteria andItemIdEqualTo(Long value) {
			addCriterion("ITEM_ID =", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdNotEqualTo(Long value) {
			addCriterion("ITEM_ID <>", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdGreaterThan(Long value) {
			addCriterion("ITEM_ID >", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ITEM_ID >=", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdLessThan(Long value) {
			addCriterion("ITEM_ID <", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdLessThanOrEqualTo(Long value) {
			addCriterion("ITEM_ID <=", value, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdIn(List<Long> values) {
			addCriterion("ITEM_ID in", values, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdNotIn(List<Long> values) {
			addCriterion("ITEM_ID not in", values, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdBetween(Long value1, Long value2) {
			addCriterion("ITEM_ID between", value1, value2, "itemId");
			return (Criteria) this;
		}

		public Criteria andItemIdNotBetween(Long value1, Long value2) {
			addCriterion("ITEM_ID not between", value1, value2, "itemId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdIsNull() {
			addCriterion("POLICY_ID is null");
			return (Criteria) this;
		}

		public Criteria andPolicyIdIsNotNull() {
			addCriterion("POLICY_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPolicyIdEqualTo(Long value) {
			addCriterion("POLICY_ID =", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdNotEqualTo(Long value) {
			addCriterion("POLICY_ID <>", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdGreaterThan(Long value) {
			addCriterion("POLICY_ID >", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdGreaterThanOrEqualTo(Long value) {
			addCriterion("POLICY_ID >=", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdLessThan(Long value) {
			addCriterion("POLICY_ID <", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdLessThanOrEqualTo(Long value) {
			addCriterion("POLICY_ID <=", value, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdIn(List<Long> values) {
			addCriterion("POLICY_ID in", values, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdNotIn(List<Long> values) {
			addCriterion("POLICY_ID not in", values, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdBetween(Long value1, Long value2) {
			addCriterion("POLICY_ID between", value1, value2, "policyId");
			return (Criteria) this;
		}

		public Criteria andPolicyIdNotBetween(Long value1, Long value2) {
			addCriterion("POLICY_ID not between", value1, value2, "policyId");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNull() {
			addCriterion("OBJECT_ID is null");
			return (Criteria) this;
		}

		public Criteria andObjectIdIsNotNull() {
			addCriterion("OBJECT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andObjectIdEqualTo(String value) {
			addCriterion("OBJECT_ID =", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotEqualTo(String value) {
			addCriterion("OBJECT_ID <>", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThan(String value) {
			addCriterion("OBJECT_ID >", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdGreaterThanOrEqualTo(String value) {
			addCriterion("OBJECT_ID >=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThan(String value) {
			addCriterion("OBJECT_ID <", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLessThanOrEqualTo(String value) {
			addCriterion("OBJECT_ID <=", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdLike(String value) {
			addCriterion("OBJECT_ID like", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotLike(String value) {
			addCriterion("OBJECT_ID not like", value, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdIn(List<String> values) {
			addCriterion("OBJECT_ID in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotIn(List<String> values) {
			addCriterion("OBJECT_ID not in", values, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdBetween(String value1, String value2) {
			addCriterion("OBJECT_ID between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andObjectIdNotBetween(String value1, String value2) {
			addCriterion("OBJECT_ID not between", value1, value2, "objectId");
			return (Criteria) this;
		}

		public Criteria andElementIdIsNull() {
			addCriterion("ELEMENT_ID is null");
			return (Criteria) this;
		}

		public Criteria andElementIdIsNotNull() {
			addCriterion("ELEMENT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andElementIdEqualTo(Long value) {
			addCriterion("ELEMENT_ID =", value, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdNotEqualTo(Long value) {
			addCriterion("ELEMENT_ID <>", value, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdGreaterThan(Long value) {
			addCriterion("ELEMENT_ID >", value, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ELEMENT_ID >=", value, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdLessThan(Long value) {
			addCriterion("ELEMENT_ID <", value, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdLessThanOrEqualTo(Long value) {
			addCriterion("ELEMENT_ID <=", value, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdIn(List<Long> values) {
			addCriterion("ELEMENT_ID in", values, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdNotIn(List<Long> values) {
			addCriterion("ELEMENT_ID not in", values, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdBetween(Long value1, Long value2) {
			addCriterion("ELEMENT_ID between", value1, value2, "elementId");
			return (Criteria) this;
		}

		public Criteria andElementIdNotBetween(Long value1, Long value2) {
			addCriterion("ELEMENT_ID not between", value1, value2, "elementId");
			return (Criteria) this;
		}

		public Criteria andMatchTypeIsNull() {
			addCriterion("MATCH_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andMatchTypeIsNotNull() {
			addCriterion("MATCH_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andMatchTypeEqualTo(String value) {
			addCriterion("MATCH_TYPE =", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeNotEqualTo(String value) {
			addCriterion("MATCH_TYPE <>", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeGreaterThan(String value) {
			addCriterion("MATCH_TYPE >", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeGreaterThanOrEqualTo(String value) {
			addCriterion("MATCH_TYPE >=", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeLessThan(String value) {
			addCriterion("MATCH_TYPE <", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeLessThanOrEqualTo(String value) {
			addCriterion("MATCH_TYPE <=", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeLike(String value) {
			addCriterion("MATCH_TYPE like", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeNotLike(String value) {
			addCriterion("MATCH_TYPE not like", value, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeIn(List<String> values) {
			addCriterion("MATCH_TYPE in", values, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeNotIn(List<String> values) {
			addCriterion("MATCH_TYPE not in", values, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeBetween(String value1, String value2) {
			addCriterion("MATCH_TYPE between", value1, value2, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchTypeNotBetween(String value1, String value2) {
			addCriterion("MATCH_TYPE not between", value1, value2, "matchType");
			return (Criteria) this;
		}

		public Criteria andMatchValueIsNull() {
			addCriterion("MATCH_VALUE is null");
			return (Criteria) this;
		}

		public Criteria andMatchValueIsNotNull() {
			addCriterion("MATCH_VALUE is not null");
			return (Criteria) this;
		}

		public Criteria andMatchValueEqualTo(String value) {
			addCriterion("MATCH_VALUE =", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueNotEqualTo(String value) {
			addCriterion("MATCH_VALUE <>", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueGreaterThan(String value) {
			addCriterion("MATCH_VALUE >", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueGreaterThanOrEqualTo(String value) {
			addCriterion("MATCH_VALUE >=", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueLessThan(String value) {
			addCriterion("MATCH_VALUE <", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueLessThanOrEqualTo(String value) {
			addCriterion("MATCH_VALUE <=", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueLike(String value) {
			addCriterion("MATCH_VALUE like", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueNotLike(String value) {
			addCriterion("MATCH_VALUE not like", value, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueIn(List<String> values) {
			addCriterion("MATCH_VALUE in", values, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueNotIn(List<String> values) {
			addCriterion("MATCH_VALUE not in", values, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueBetween(String value1, String value2) {
			addCriterion("MATCH_VALUE between", value1, value2, "matchValue");
			return (Criteria) this;
		}

		public Criteria andMatchValueNotBetween(String value1, String value2) {
			addCriterion("MATCH_VALUE not between", value1, value2, "matchValue");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdIsNull() {
			addCriterion("UPDATE_DEPT_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdIsNotNull() {
			addCriterion("UPDATE_DEPT_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdEqualTo(String value) {
			addCriterion("UPDATE_DEPT_ID =", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdNotEqualTo(String value) {
			addCriterion("UPDATE_DEPT_ID <>", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdGreaterThan(String value) {
			addCriterion("UPDATE_DEPT_ID >", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_DEPT_ID >=", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdLessThan(String value) {
			addCriterion("UPDATE_DEPT_ID <", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_DEPT_ID <=", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdLike(String value) {
			addCriterion("UPDATE_DEPT_ID like", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdNotLike(String value) {
			addCriterion("UPDATE_DEPT_ID not like", value, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdIn(List<String> values) {
			addCriterion("UPDATE_DEPT_ID in", values, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdNotIn(List<String> values) {
			addCriterion("UPDATE_DEPT_ID not in", values, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdBetween(String value1, String value2) {
			addCriterion("UPDATE_DEPT_ID between", value1, value2, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateDeptIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_DEPT_ID not between", value1, value2, "updateDeptId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdIsNull() {
			addCriterion("UPDATE_OPER_ID is null");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdIsNotNull() {
			addCriterion("UPDATE_OPER_ID is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdEqualTo(String value) {
			addCriterion("UPDATE_OPER_ID =", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdNotEqualTo(String value) {
			addCriterion("UPDATE_OPER_ID <>", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdGreaterThan(String value) {
			addCriterion("UPDATE_OPER_ID >", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdGreaterThanOrEqualTo(String value) {
			addCriterion("UPDATE_OPER_ID >=", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdLessThan(String value) {
			addCriterion("UPDATE_OPER_ID <", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdLessThanOrEqualTo(String value) {
			addCriterion("UPDATE_OPER_ID <=", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdLike(String value) {
			addCriterion("UPDATE_OPER_ID like", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdNotLike(String value) {
			addCriterion("UPDATE_OPER_ID not like", value, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdIn(List<String> values) {
			addCriterion("UPDATE_OPER_ID in", values, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdNotIn(List<String> values) {
			addCriterion("UPDATE_OPER_ID not in", values, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdBetween(String value1, String value2) {
			addCriterion("UPDATE_OPER_ID between", value1, value2, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateOperIdNotBetween(String value1, String value2) {
			addCriterion("UPDATE_OPER_ID not between", value1, value2, "updateOperId");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andDataFormatIsNull() {
			addCriterion("DATA_FORMAT is null");
			return (Criteria) this;
		}

		public Criteria andDataFormatIsNotNull() {
			addCriterion("DATA_FORMAT is not null");
			return (Criteria) this;
		}

		public Criteria andDataFormatEqualTo(String value) {
			addCriterion("DATA_FORMAT =", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatNotEqualTo(String value) {
			addCriterion("DATA_FORMAT <>", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatGreaterThan(String value) {
			addCriterion("DATA_FORMAT >", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatGreaterThanOrEqualTo(String value) {
			addCriterion("DATA_FORMAT >=", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatLessThan(String value) {
			addCriterion("DATA_FORMAT <", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatLessThanOrEqualTo(String value) {
			addCriterion("DATA_FORMAT <=", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatLike(String value) {
			addCriterion("DATA_FORMAT like", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatNotLike(String value) {
			addCriterion("DATA_FORMAT not like", value, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatIn(List<String> values) {
			addCriterion("DATA_FORMAT in", values, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatNotIn(List<String> values) {
			addCriterion("DATA_FORMAT not in", values, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatBetween(String value1, String value2) {
			addCriterion("DATA_FORMAT between", value1, value2, "dataFormat");
			return (Criteria) this;
		}

		public Criteria andDataFormatNotBetween(String value1, String value2) {
			addCriterion("DATA_FORMAT not between", value1, value2, "dataFormat");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table stl_policy_item_condition
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stl_policy_item_condition
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 13 15:20:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}