package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlPolicyItemCondition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.CONDITION_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private Long conditionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.TENANT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.ITEM_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private Long itemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.POLICY_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private Long policyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.OBJECT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String objectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.ELEMENT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private Long elementId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.MATCH_TYPE
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String matchType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.MATCH_VALUE
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String matchValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.UPDATE_DEPT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String updateDeptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.UPDATE_OPER_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String updateOperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.UPDATE_TIME
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_item_condition.DATA_FORMAT
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	private String dataFormat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.CONDITION_ID
	 * @return  the value of stl_policy_item_condition.CONDITION_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Long getConditionId() {
		return conditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.CONDITION_ID
	 * @param conditionId  the value for stl_policy_item_condition.CONDITION_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setConditionId(Long conditionId) {
		this.conditionId = conditionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.TENANT_ID
	 * @return  the value of stl_policy_item_condition.TENANT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.TENANT_ID
	 * @param tenantId  the value for stl_policy_item_condition.TENANT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.ITEM_ID
	 * @return  the value of stl_policy_item_condition.ITEM_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Long getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.ITEM_ID
	 * @param itemId  the value for stl_policy_item_condition.ITEM_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.POLICY_ID
	 * @return  the value of stl_policy_item_condition.POLICY_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.POLICY_ID
	 * @param policyId  the value for stl_policy_item_condition.POLICY_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setPolicyId(Long policyId) {
		this.policyId = policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.OBJECT_ID
	 * @return  the value of stl_policy_item_condition.OBJECT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getObjectId() {
		return objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.OBJECT_ID
	 * @param objectId  the value for stl_policy_item_condition.OBJECT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.ELEMENT_ID
	 * @return  the value of stl_policy_item_condition.ELEMENT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Long getElementId() {
		return elementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.ELEMENT_ID
	 * @param elementId  the value for stl_policy_item_condition.ELEMENT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setElementId(Long elementId) {
		this.elementId = elementId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.MATCH_TYPE
	 * @return  the value of stl_policy_item_condition.MATCH_TYPE
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getMatchType() {
		return matchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.MATCH_TYPE
	 * @param matchType  the value for stl_policy_item_condition.MATCH_TYPE
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setMatchType(String matchType) {
		this.matchType = matchType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.MATCH_VALUE
	 * @return  the value of stl_policy_item_condition.MATCH_VALUE
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getMatchValue() {
		return matchValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.MATCH_VALUE
	 * @param matchValue  the value for stl_policy_item_condition.MATCH_VALUE
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setMatchValue(String matchValue) {
		this.matchValue = matchValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.UPDATE_DEPT_ID
	 * @return  the value of stl_policy_item_condition.UPDATE_DEPT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getUpdateDeptId() {
		return updateDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.UPDATE_DEPT_ID
	 * @param updateDeptId  the value for stl_policy_item_condition.UPDATE_DEPT_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setUpdateDeptId(String updateDeptId) {
		this.updateDeptId = updateDeptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.UPDATE_OPER_ID
	 * @return  the value of stl_policy_item_condition.UPDATE_OPER_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getUpdateOperId() {
		return updateOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.UPDATE_OPER_ID
	 * @param updateOperId  the value for stl_policy_item_condition.UPDATE_OPER_ID
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setUpdateOperId(String updateOperId) {
		this.updateOperId = updateOperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.UPDATE_TIME
	 * @return  the value of stl_policy_item_condition.UPDATE_TIME
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.UPDATE_TIME
	 * @param updateTime  the value for stl_policy_item_condition.UPDATE_TIME
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_item_condition.DATA_FORMAT
	 * @return  the value of stl_policy_item_condition.DATA_FORMAT
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public String getDataFormat() {
		return dataFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_item_condition.DATA_FORMAT
	 * @param dataFormat  the value for stl_policy_item_condition.DATA_FORMAT
	 * @mbg.generated  Wed Jul 25 16:09:47 CST 2018
	 */
	public void setDataFormat(String dataFormat) {
		this.dataFormat = dataFormat;
	}
}