package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlPolicyItemPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.PLAN_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.ITEM_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.POLICY_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long policyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.OBJECT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.ELEMENT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Long elementId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.FEE_ITEM
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String feeItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.PLAN_TYPE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String planType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.CAL_TYPE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String calType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.CAL_VALUE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String calValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String updateDeptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String updateOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stl_policy_item_plan.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.PLAN_ID
     *
     * @return the value of stl_policy_item_plan.PLAN_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.PLAN_ID
     *
     * @param planId the value for stl_policy_item_plan.PLAN_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.TENANT_ID
     *
     * @return the value of stl_policy_item_plan.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.TENANT_ID
     *
     * @param tenantId the value for stl_policy_item_plan.TENANT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.ITEM_ID
     *
     * @return the value of stl_policy_item_plan.ITEM_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.ITEM_ID
     *
     * @param itemId the value for stl_policy_item_plan.ITEM_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.POLICY_ID
     *
     * @return the value of stl_policy_item_plan.POLICY_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getPolicyId() {
        return policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.POLICY_ID
     *
     * @param policyId the value for stl_policy_item_plan.POLICY_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setPolicyId(Long policyId) {
        this.policyId = policyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.OBJECT_ID
     *
     * @return the value of stl_policy_item_plan.OBJECT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.OBJECT_ID
     *
     * @param objectId the value for stl_policy_item_plan.OBJECT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.ELEMENT_ID
     *
     * @return the value of stl_policy_item_plan.ELEMENT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Long getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.ELEMENT_ID
     *
     * @param elementId the value for stl_policy_item_plan.ELEMENT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setElementId(Long elementId) {
        this.elementId = elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.FEE_ITEM
     *
     * @return the value of stl_policy_item_plan.FEE_ITEM
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getFeeItem() {
        return feeItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.FEE_ITEM
     *
     * @param feeItem the value for stl_policy_item_plan.FEE_ITEM
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setFeeItem(String feeItem) {
        this.feeItem = feeItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.PLAN_TYPE
     *
     * @return the value of stl_policy_item_plan.PLAN_TYPE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getPlanType() {
        return planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.PLAN_TYPE
     *
     * @param planType the value for stl_policy_item_plan.PLAN_TYPE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setPlanType(String planType) {
        this.planType = planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.CAL_TYPE
     *
     * @return the value of stl_policy_item_plan.CAL_TYPE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCalType() {
        return calType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.CAL_TYPE
     *
     * @param calType the value for stl_policy_item_plan.CAL_TYPE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCalType(String calType) {
        this.calType = calType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.CAL_VALUE
     *
     * @return the value of stl_policy_item_plan.CAL_VALUE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getCalValue() {
        return calValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.CAL_VALUE
     *
     * @param calValue the value for stl_policy_item_plan.CAL_VALUE
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setCalValue(String calValue) {
        this.calValue = calValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.UPDATE_DEPT_ID
     *
     * @return the value of stl_policy_item_plan.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getUpdateDeptId() {
        return updateDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.UPDATE_DEPT_ID
     *
     * @param updateDeptId the value for stl_policy_item_plan.UPDATE_DEPT_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateDeptId(String updateDeptId) {
        this.updateDeptId = updateDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.UPDATE_OPER_ID
     *
     * @return the value of stl_policy_item_plan.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getUpdateOperId() {
        return updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.UPDATE_OPER_ID
     *
     * @param updateOperId the value for stl_policy_item_plan.UPDATE_OPER_ID
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateOperId(String updateOperId) {
        this.updateOperId = updateOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stl_policy_item_plan.UPDATE_TIME
     *
     * @return the value of stl_policy_item_plan.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stl_policy_item_plan.UPDATE_TIME
     *
     * @param updateTime the value for stl_policy_item_plan.UPDATE_TIME
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}