package com.x.ic.msg.dao.mapper.bo;

import java.util.Date;

public class StlPolicyTaskCycle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.POLICY_CYCLE_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String policyCycleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.POLICY_CYCLE_CODE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String policyCycleCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.POLICY_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private Long policyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.OBJECT_TYPE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String objectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.OBJECT_CODE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String objectCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.START_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.END_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.STATUS
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.TENANT_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String tenantId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.CREATE_DATE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.UPDATE_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.CREATE_STAFF_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String createStaffId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column stl_policy_task_cycle.CYCLE_VALUE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	private String cycleValue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.POLICY_CYCLE_ID
	 * @return  the value of stl_policy_task_cycle.POLICY_CYCLE_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getPolicyCycleId() {
		return policyCycleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.POLICY_CYCLE_ID
	 * @param policyCycleId  the value for stl_policy_task_cycle.POLICY_CYCLE_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setPolicyCycleId(String policyCycleId) {
		this.policyCycleId = policyCycleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.POLICY_CYCLE_CODE
	 * @return  the value of stl_policy_task_cycle.POLICY_CYCLE_CODE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getPolicyCycleCode() {
		return policyCycleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.POLICY_CYCLE_CODE
	 * @param policyCycleCode  the value for stl_policy_task_cycle.POLICY_CYCLE_CODE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setPolicyCycleCode(String policyCycleCode) {
		this.policyCycleCode = policyCycleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.POLICY_ID
	 * @return  the value of stl_policy_task_cycle.POLICY_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public Long getPolicyId() {
		return policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.POLICY_ID
	 * @param policyId  the value for stl_policy_task_cycle.POLICY_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setPolicyId(Long policyId) {
		this.policyId = policyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.OBJECT_TYPE
	 * @return  the value of stl_policy_task_cycle.OBJECT_TYPE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getObjectType() {
		return objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.OBJECT_TYPE
	 * @param objectType  the value for stl_policy_task_cycle.OBJECT_TYPE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.OBJECT_CODE
	 * @return  the value of stl_policy_task_cycle.OBJECT_CODE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getObjectCode() {
		return objectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.OBJECT_CODE
	 * @param objectCode  the value for stl_policy_task_cycle.OBJECT_CODE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setObjectCode(String objectCode) {
		this.objectCode = objectCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.START_TIME
	 * @return  the value of stl_policy_task_cycle.START_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.START_TIME
	 * @param startTime  the value for stl_policy_task_cycle.START_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.END_TIME
	 * @return  the value of stl_policy_task_cycle.END_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.END_TIME
	 * @param endTime  the value for stl_policy_task_cycle.END_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.STATUS
	 * @return  the value of stl_policy_task_cycle.STATUS
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.STATUS
	 * @param status  the value for stl_policy_task_cycle.STATUS
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.TENANT_ID
	 * @return  the value of stl_policy_task_cycle.TENANT_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getTenantId() {
		return tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.TENANT_ID
	 * @param tenantId  the value for stl_policy_task_cycle.TENANT_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.CREATE_DATE
	 * @return  the value of stl_policy_task_cycle.CREATE_DATE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.CREATE_DATE
	 * @param createDate  the value for stl_policy_task_cycle.CREATE_DATE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.UPDATE_TIME
	 * @return  the value of stl_policy_task_cycle.UPDATE_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.UPDATE_TIME
	 * @param updateTime  the value for stl_policy_task_cycle.UPDATE_TIME
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.CREATE_STAFF_ID
	 * @return  the value of stl_policy_task_cycle.CREATE_STAFF_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getCreateStaffId() {
		return createStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.CREATE_STAFF_ID
	 * @param createStaffId  the value for stl_policy_task_cycle.CREATE_STAFF_ID
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setCreateStaffId(String createStaffId) {
		this.createStaffId = createStaffId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column stl_policy_task_cycle.CYCLE_VALUE
	 * @return  the value of stl_policy_task_cycle.CYCLE_VALUE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public String getCycleValue() {
		return cycleValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column stl_policy_task_cycle.CYCLE_VALUE
	 * @param cycleValue  the value for stl_policy_task_cycle.CYCLE_VALUE
	 * @mbg.generated  Fri Aug 03 16:38:50 CST 2018
	 */
	public void setCycleValue(String cycleValue) {
		this.cycleValue = cycleValue;
	}
}