package com.x.ic.msg.dao.mapper.bo;

public class StlRecordFormat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.tenant_id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.service_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String serviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.source
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.format_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Short formatType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.field_serial
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Integer fieldSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.field_name
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.field_code
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String fieldCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.data_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.remark
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.nullable
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String nullable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.is_sn
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private String isSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phd_record_format.seq_no
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    private Integer seqNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.id
     *
     * @return the value of phd_record_format.id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.id
     *
     * @param id the value for phd_record_format.id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.tenant_id
     *
     * @return the value of phd_record_format.tenant_id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.tenant_id
     *
     * @param tenantId the value for phd_record_format.tenant_id
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.service_type
     *
     * @return the value of phd_record_format.service_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.service_type
     *
     * @param serviceType the value for phd_record_format.service_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.source
     *
     * @return the value of phd_record_format.source
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.source
     *
     * @param source the value for phd_record_format.source
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.format_type
     *
     * @return the value of phd_record_format.format_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Short getFormatType() {
        return formatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.format_type
     *
     * @param formatType the value for phd_record_format.format_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setFormatType(Short formatType) {
        this.formatType = formatType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.field_serial
     *
     * @return the value of phd_record_format.field_serial
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Integer getFieldSerial() {
        return fieldSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.field_serial
     *
     * @param fieldSerial the value for phd_record_format.field_serial
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setFieldSerial(Integer fieldSerial) {
        this.fieldSerial = fieldSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.field_name
     *
     * @return the value of phd_record_format.field_name
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.field_name
     *
     * @param fieldName the value for phd_record_format.field_name
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.field_code
     *
     * @return the value of phd_record_format.field_code
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.field_code
     *
     * @param fieldCode the value for phd_record_format.field_code
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.data_type
     *
     * @return the value of phd_record_format.data_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.data_type
     *
     * @param dataType the value for phd_record_format.data_type
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.remark
     *
     * @return the value of phd_record_format.remark
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.remark
     *
     * @param remark the value for phd_record_format.remark
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.nullable
     *
     * @return the value of phd_record_format.nullable
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getNullable() {
        return nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.nullable
     *
     * @param nullable the value for phd_record_format.nullable
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setNullable(String nullable) {
        this.nullable = nullable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.is_sn
     *
     * @return the value of phd_record_format.is_sn
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public String getIsSn() {
        return isSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.is_sn
     *
     * @param isSn the value for phd_record_format.is_sn
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setIsSn(String isSn) {
        this.isSn = isSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phd_record_format.seq_no
     *
     * @return the value of phd_record_format.seq_no
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phd_record_format.seq_no
     *
     * @param seqNo the value for phd_record_format.seq_no
     *
     * @mbg.generated Tue Jun 12 14:46:39 CST 2018
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }
}